Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (19445, 'COPO CP330BI000/1CC ALL PARMEGIANA TRAD.', 'CP330BI000/1CC', 110, 10, 
    '2010-07-27');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (19070, 'COPO CP330BI000/1CC COCA-COLA PETISKEIRA', 'CP330BI000/1CC', 118.36, 10, 
    '2010-07-13');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (19135, 'COPO CP330BI004 1000UC MEGA DOG PRENSADO', 'CP330BI004', 55, 4, 
    '2010-07-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (71943, 'POTE PP200T0000/1 1000UC 4 GR', 'PP200T0000/1', 49.43, 4, 
    '2003-08-02');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (18783, 'COPO CP200BI/ABNT/L 3000UC CENTROCARDIO', 'CP200BI/ABNT/L', 113, 6.6, 
    '2010-06-17');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (18848, 'COPO C110IC/2 3000UC ICE COLA', 'C110IC/2', 151.71, 5.7, 
    '2010-06-22');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89729, 'COPO CP330BI003 RHELK''S 2010', 'CP330BI003', 103, 8, 
    '2005-08-30');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (17957, 'POTE PP300BI001/1 1000UC RHELK''S 2010', 'PP300BI001/1', 115, 7.5, 
    '2010-05-21');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (16276, 'POTE PB250PI001/1 SORVELANDIA SORVERION', 'PB250PI001/1', 88, 4.8, 
    '2010-02-26');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (13226, 'POTE PP160TI000 URCA CHOCOLATE/MORANGO', 'PP160TI000', 76.7, 5, 
    '2008-05-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (13129, 'POTE PP160TI000 1000UC KUKA FRIA FLOC/CH', 'PP160TI000', 79.5, 5, 
    '2008-05-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89494, 'COPO CP400B/ABNT 1000UC', 'CP400B/ABNT', 52.8, 5, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (10685, 'COPO CP330BI000/1CC COCA-COLA PADRAO', 'CP330BI000/1CC', 118.36, 10, 
    '2007-12-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (10790, 'POTE PP340BI000/2 1000UC URCA LARANJA', 'PP340BI000/2', 105, 6.5, 
    '2007-12-19');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (10340, 'COPO CP330TI000/1CC 2000UC MILKTALY', 'CP330TI000/1CC', 130, 10, 
    '2007-11-30');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (9920, 'POTE PP340BI000/2 REFRESKATA 2010', 'PP340BI000/2', 106, 6.5, 
    '2007-11-16');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (9997, 'POTE PP500BI003/1 DOCE DOCE CAFE', 'PP500BI003/1', 120.7, 7.5, 
    '2007-11-20');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (9822, 'POTE PP340BI000/2 1000UC DOCE DOCE CAFE', 'PP340BI000/2', 105, 6.5, 
    '2007-11-16');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (9601, 'POTE PP160TI000 1000UC URCA CHOCOLATE', 'PP160TI000', 76.7, 5, 
    '2007-11-05');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (9628, 'POTE PP160TI000 1000UC URCA CREME', 'PP160TI000', 76.7, 5, 
    '2007-11-05');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (9636, 'POTE PP160TI000 1000UC URCA MORANGO', 'PP160TI000', 76.7, 5, 
    '2007-11-05');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (8818, 'POTE C100ES 2000UC', 'C100ES', 35, 2.5, 
    '2007-10-05');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (8826, 'POTE C100TES 2000UC', 'C100TES', 35, 2.5, 
    '2007-10-05');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (8834, 'COPO CP550BI000 900UC LOJAS AMERICANAS', 'CP550BI000', 92.97, 6.75, 
    '2007-10-08');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (7609, 'COPO CP330TI001 1000 SORVETERIA DO JO', 'CP330TI001', 56, 4, 
    '2007-08-09');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (7170, 'COPO CP330BI000/1CC 2000UC  VIENA', 'CP330BI000/1CC', 116.87, 10, 
    '2007-07-11');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (6769, 'COPO CP300B/ABNT/FMT/1-CX 2000UC', 'CP300B/ABNT/FMT/1', 84.98, 6.6, 
    '2007-06-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (6696, 'COPO CP180BES/ABNT/FMT/1-CX 2500UC', 'CP180BES/ABNT/FMT/1', 59.65, 4.95, 
    '2007-06-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (6726, 'COPO CP200BES/ABNT/FMT/1-CX 2500UC', 'CP200BES/ABNT/FMT/1', 74.26, 5.5, 
    '2007-06-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (6300, 'COPO CP330BI003 SFIHA GRILL F/AMARELO', 'CP330BI003', 105, 8, 
    '2007-05-15');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (6211, 'PP340TI000/1 CHIQUINHO MILSHAKE 2007', 'PP340TI000/1', 110, 7.5, 
    '2007-05-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (6220, 'PT250PI001/1 CHIQUINHO MILKSHAKE 2010', 'PT250PI001/1', 64, 4.8, 
    '2007-05-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (6173, 'COPO CP330BI004 1000UC CAMARAO E CIA', 'CP330BI004', 54.18, 4, 
    '2007-05-11');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (6181, 'COPO CP550TI000 CHIQUINHO MILKSHAKE 2010', 'CP550TI000', 124.84, 6.75, 
    '2007-05-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (6190, 'CP440TI/ABNT CHIQUINHO MILKSHAKE 2010', 'CP440TI/ABNT', 104.9, 5.54, 
    '2007-05-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (5916, 'COPO CP330BI003 2000UC  BISTEK', 'CP330BI003', 121.21, 8, 
    '2007-04-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (15652, 'POTE PB250PI001/1 1000UC CLAERRO 2010', 'PB250PI001/1', 90, 4.8, 
    '2010-01-05');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (15660, 'POTE PP500BI003/1 1000UC CLAERRO 2013', 'PP500BI003/1', 145, 7.5, 
    '2010-01-05');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (5720, 'COPO CP550BI000 900UC BIG NECTAR', 'CP550BI000', 99.22, 6.75, 
    '2007-04-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (5487, 'PP160TI000/1 CHIQUINHO 2010 EM MANGA', 'PP160TI000/1', 79.8, 4, 
    '2007-04-04');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89460, 'COPO CP300T/SM/ABNT 2000UC 40X50', 'CP300T/SM/ABNT', 60.39, 6.6, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (15270, 'POTE PP300TI000/1 SALAD.FRUTAS MEGA MATE', 'PP300TI000/1', 140.7, 7.5, 
    '2009-12-11');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (15369, 'POTE PP500TI003/1 SALAD.FRUTAS MEGA MATE', 'PP500TI003/1', 149.52, 7.5, 
    '2009-12-11');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (14869, 'COPO CP200BI/ABNT/L  SPIDER MAN JUNCO', 'CP200BI/ABNT/L', 96.36, 6.6, 
    '2009-12-07');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (88882, 'POTE PP PADRAO', 'PP PADRAO', 107, 1, 
    '2009-10-01');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (99992, 'COPO CP PADRAO', 'CP PADRAO', 105, 3, 
    '2009-10-01');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (99991, 'COPO CP PADRAO', 'CP PADRAO', 140.45, 3, 
    '2009-10-01');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (88883, 'POTE PP PADRAO', 'PP PADRAO', 107, 1, 
    '2009-10-01');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (99990, 'COPO CP PADRAO', 'CP PADRAO', 114, 3, 
    '2009-10-01');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (88881, 'POTE PP PADRAO', 'PP PADRAO', 107, 1, 
    '2009-10-01');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (13048, 'COPO CP330BI003 2000UC GRAAL 2008', 'CP330BI003', 105, 8, 
    '2009-11-17');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (12572, 'POTE PP400BI000/2 1000UC COPAO ESKIMO', 'PP400BI000/2', 95.3, 6.5, 
    '2009-11-11');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (8346, 'COPO CP550BI000 900UC SUCO BAGACO 2009', 'CP550BI000', 98.45, 6.75, 
    '2009-10-15');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (6718, 'COPO CP440BI/ABNT 1000U PAPA TUTTY', 'CP440BI/ABNT', 77, 5.54, 
    '2009-09-30');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (88888, 'POTE PP PADRAO ', 'PP PADRAO', 113, 1, 
    '2009-10-01');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (99999, 'COPO CP PADRAO', 'CP PADRAO', 105, 3, 
    '2009-10-01');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (3794, 'COPO CP440TI/SCHIN OKTOBERFEST IGREJINHA', 'CP440TI/ABNT', 77.8, 5.54, 
    '2009-09-22');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (3808, ' PT200PI000 CHIQUINHO SORVETES 2010', 'PT200PI000', 68.25, 3.2, 
    '2009-09-23');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (3417, 'POTE PP120BI000/1 SORVETE TOC FRIO 2009', 'PP120BI000/1', 104.5, 5.2, 
    '2009-09-02');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (3301, 'COPO CP330TI002 2000UC DOCAS', 'CP330TI002', 120, 8, 
    '2009-08-28');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (2984, 'COPO CP440TI/ABNT MILKSHAKE PADRAO DZT', 'CP440TI/ABNT', 80, 5.54, 
    '2009-08-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (2453, 'POTE PB250PI001/1 HABIB''S CNPJ 0001-80', 'PB250PI001/1', 63, 4.8, 
    '2009-07-22');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (2470, 'COPO CP330TI000/1CC PIZZA HUT / PEPSI', 'CP330TI000/1CC', 116.27, 10, 
    '2009-07-27');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (1880, 'COPO CP330TI001 HANGAI COZINHA ORIENTAL', 'CP330TI001', 65.1, 4, 
    '2009-06-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (1732, 'COPO CP550TI000 900 PIZZA HUT / PEPSI', 'CP550TI000', 87.42, 6.75, 
    '2009-06-08');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (43320, 'POTE PP500B0000 500ML BRANCO 1000UC', 'PP500B0000', 154.7, 13.5, 
    '1999-02-11');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (43664, 'POTE 450ML TRANSPARENTE 1000UC C/MANGA', 'PP450T0001', 116, 10, 
    '1999-03-17');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (44431, 'POTE PP500BI000 TEMP NAPANELA ALHO SAL', 'PP500BI000', 166, 13.5, 
    '1999-04-23');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (4863, 'COPO CP180BES/ABNT/FMT 2500UC', 'CP180BES/ABNT/FMT', 59.65, 4.95, 
    '2007-02-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (4880, 'COPO CP200BES/ABNT/FMT 2500UC', 'CP200BES/ABNT/FMT', 66.27, 5.5, 
    '2007-02-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (4898, 'COPO CP200BES/SM/ABNT 2500UC BRANCO', 'CP200BES/SM/ABNT', 52.9, 5.5, 
    '2007-02-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (4901, 'COPO CP200TES/SM/ABNT 2500UC TRANSP.', 'CP200TES/SM/ABNT', 52.9, 5.5, 
    '2007-02-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (1465, 'COPO CP330BI003 2000UC GRILETTO 2012', 'CP330BI003', 130.9, 8, 
    '2009-05-21');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (16853, 'COPO CP330TI000 CHIQUINHO MILKSHAKE 2010', 'CP330TI000', 75.6, 5, 
    '2008-09-11');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (45047, 'POTE PP500BI000 TEMP. NAPANELA C/PIMENTA', 'PP500BI000', 166, 13.5, 
    '1999-05-24');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (1007, 'POTE PP200TI000/2 AGUA SANTA CATARINA/1', 'PP200TI000/2', 61.6, 4.2, 
    '2009-04-03');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (1066, 'COPO CP200BI/ABNT/L GRILETTO 2012', 'CP200BI/ABNT/L', 112.42, 6.6, 
    '2009-04-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (876, 'COPO CP330BI003 2000UC CORREA BACK', 'CP330BI003', 110, 8, 
    '2009-03-31');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (671, 'COPO CP440BI/ABNT 1000UC GRILETTO 2012', 'CP440BI/ABNT', 92.67, 5.64, 
    '2009-03-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (680, 'COPO CP550BI000 900UC GRILETTO 2012', 'CP550BI000', 107.35, 6.75, 
    '2009-03-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (64114, 'COPO CP330BI003  IMBRALIT CASA AGUA', 'CP330BI003', 125, 8, 
    '2002-08-30');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (65765, 'TAMPA TP100B0003 BRANCO  C/ MANGA 1000UC', 'TP100B0003', 65.45, 3.3, 
    '2002-10-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (65773, 'TAMPA TP100T0003 TRANSP. C/ MANGA 1000UC', 'TP100T0003', 58, 3.3, 
    '2002-10-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (65803, 'TAMPA TP101B0003 BRANCA C/ MANGA 1000UC', 'TP101B0003', 52, 3.3, 
    '2002-10-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (65811, 'TAMPA TP101T0003 TRANSP. C/ MANGA 1000UC', 'TP101T0003', 60.3, 3.3, 
    '2002-10-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (67814, 'PRATO FUNDO 210MM 500UC 50X10', 'PF210/1', 42.9, 3.48, 
    '2002-12-12');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (70106, 'COPO CZ50C/ABNT 50ML 5000UC', 'CZ50C/ABNT', 39.09, 3.75, 
    '2003-04-04');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (71480, 'COPO CP300ABNT/1 2000UC LINHA OURO', 'CP300ABNT/1', 53.27, 6.6, 
    '2003-07-17');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (71498, 'COPO CP300SM/ABNT/1 2000UC 40X50', 'CP300SM/ABNT/1', 60.39, 6.6, 
    '2003-07-17');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (71730, 'POTE PP160T0001/1 1000UC MANGA', 'PP160T0001/1', 48.2, 4, 
    '2003-07-26');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (71765, 'TAMPA TP25T0001/1 1000UC MANGA', 'TP25T0001/1', 37.3, 2, 
    '2003-07-26');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (71811, 'POTE PP300T0003/1 1000UC MANGA 4,7 GR', 'PP300T0003/1', 62, 4.7, 
    '2003-07-29');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (71838, 'POTE PP450T0001/1 1000UC MANGA 7,5 GR', 'PP450T0001/1', 90, 7.5, 
    '2003-07-29');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (72001, 'POTE PP340T0000/1 1000UC 7,5 GR', 'PP340T0000/1', 95.72, 7.5, 
    '2003-08-02');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (72010, 'POTE PP340T0001/1 1000UC 4,7 GR', 'PP340T0001/1', 76, 4.7, 
    '2003-08-02');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (72044, 'POTE PP400T0000/1 1000UC 7,5 GR', 'PP400T0000/1', 98.5, 7.5, 
    '2003-08-02');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (73288, 'COPO CP330TL003 1000UC LISO', 'CP330TL003', 36.7, 4, 
    '2003-09-12');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (73296, 'COPO CP330BL002 1000UC LISO', 'CP330BL002', 36.6, 4, 
    '2003-09-12');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (73490, 'COPO CP200BES/ABNT 2500UC LINHA OURO', 'CP200BES/ABNT', 46.39, 5.5, 
    '2003-09-17');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (75930, 'POTE PP500BI003/1 DOCE CROCHEMORE', 'PP500BI003/1', 143.73, 7.5, 
    '2004-01-05');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (77267, 'POTE PB250P0001/1 1000UC', 'PB250P0001/1', 47.79, 3.2, 
    '2004-03-31');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (77275, 'POTE PT250P0001/1 1000UC', 'PT250P0001/1', 45.3, 3.2, 
    '2004-03-31');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (77470, 'POTE PP160TI000 SUNDAE ITALIANA CHOCOLA', 'PP160TI000', 86.35, 5, 
    '2004-04-15');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (77810, 'TAMPA TB79/1 2000UC', 'TB79/1', 51.33, 2.8, 
    '2004-05-10');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (77828, 'TAMPA TS06/1 2000UC', 'TS06/1', 45, 2.4, 
    '2004-05-10');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (78360, 'COPO CP550BI000 900UC HABIBS', 'CP550BI000', 79, 6.75, 
    '2004-06-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (78549, 'TAMPA TB79F/2 2000UC BRANCA', 'TB79F/2', 51, 2.8, 
    '2004-07-02');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (78557, 'TAMPA TS06TT/2 2000UC', 'TS06TT/2', 45, 2.4, 
    '2004-07-02');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (79570, 'POTE PT200P0001 1000UC', 'PT200P0001', 35, 2.8, 
    '2004-08-27');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (81051, 'POTE PP100T0000/1 2000UC', 'PP100T0000/1', 59.88, 4.2, 
    '2004-10-20');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (81094, 'POTE PP100ML BRANCO 2000UC', 'PP100B0000/1', 46.2, 4.2, 
    '2004-10-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (81353, 'POTE PP500B0004/2 1000UC', 'PP500B0004/2', 107.89, 6.5, 
    '2004-11-04');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (81361, 'POTE PP500T0004/2 1000UC', 'PP500T0004/2', 90.2, 6.5, 
    '2004-11-04');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (81396, 'COPO CP180BES/ABNT 2500UC LINHA OURO', 'CP180BES/ABNT', 47.73, 4.95, 
    '2004-11-05');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (81728, 'POTE PP120B0000 2000UC', 'PP120B0000', 79.33, 5.2, 
    '2004-11-12');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (81736, 'POTE PP120T0000 2000UC', 'PP120T0000', 63, 5.2, 
    '2004-11-12');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (82490, 'POTE PP160TI000/1 FRIBOM NOVO', 'PP160TI000/1', 77.69, 4, 
    '2004-12-15');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (83470, 'COPO CP330BI003 2000UC BIG NECTAR', 'CP330BI003', 115.5, 8, 
    '2005-02-01');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (83704, 'TAMPA TP25T0001/2 1000UC', 'TP25T0001/2', 63.65, 3.2, 
    '2005-02-11');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (84093, 'COPO CP330BI003 2000UC KANSAS GRILL', 'CP330BI003', 114, 8, 
    '2005-03-04');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (84778, 'COPO CP150BES/ABNT 2500UC-LINHA OURO', 'CP150BES/ABNT', 37.11, 4.13, 
    '2005-03-30');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (85480, 'COPO CP200T/SM2/ABNT 2000UC 25X25', 'CP200T/SM2/ABNT', 40.26, 4.4, 
    '2005-04-26');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (85707, 'COPO CP550TI000 PILAR GRILL NOVO', 'CP550TI000', 101, 6.75, 
    '2005-05-06');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (85944, 'COPO CP300T/ABNT 2000UC LINHA OURO', 'CP300T/ABNT', 62.5, 6.6, 
    '2005-05-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (86002, 'COPO CP550BI000 RHELK''S 2010', 'CP550BI000', 83, 6.75, 
    '2005-05-19');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (86541, 'COPO CP330TI002 PILAR GRILL NOVO', 'CP330TI002', 116, 8, 
    '2005-06-10');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (86622, 'COPO CP200B/SM2/ABNT 2000UC 25X25', 'CP200B/SM2/ABNT', 58.49, 4.4, 
    '2005-06-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (86630, 'COPO CP300B/SM2/ABNT 1000UC 25X25', 'CP300B/SM2/ABNT', 46.71, 3.3, 
    '2005-06-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (86649, 'COPO CP300T/SM2/ABNT 1000UC 25X25', 'CP300T/SM2/ABNT', 43, 3.3, 
    '2005-06-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (86800, 'TAMPA TT79F/1 2000UC TRANSPARENTE FURADA', 'TT79F/1', 59.9, 2.8, 
    '2005-06-17');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (87750, 'COPO CP330BI004 RESTAURANTE HO CHI MINH', 'CP330BI004', 60, 4, 
    '2005-07-15');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (88510, 'POTE PP400T0002 1000UC TRANSPARENTE', 'PP400T0002', 135, 13.5, 
    '2005-08-04');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89184, 'PRATO PF120/3 1000UC', 'PF120/3', 30.81, 2.4, 
    '2005-08-23');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89192, 'PRATO PF150/4 1000UC', 'PF150/4', 39.9, 3.5, 
    '2005-08-23');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89206, 'PRATO PR150/3 1000UC', 'PR150/3', 34.82, 3, 
    '2005-08-23');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89222, 'PRATO PR210/3 500UC', 'PR210/3', 35.8, 3, 
    '2005-08-23');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89389, 'COPO CP150TES/ABNT 2500UC LINHA OURO', 'CP150TES/ABNT', 34.19, 4.13, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89427, 'COPO CP200TES/ABNT 2500UC LINHA OURO', 'CP200TES/ABNT', 51.65, 5.5, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89486, 'COPO CP330T/ABNT 1000UC', 'CP330T/ABNT', 33, 3.63, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89508, 'COPO CP400T/ABNT 1000UC', 'CP400T/ABNT', 55, 5, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89516, 'COPO CP440B/ABNT 1000UC', 'CP440B/ABNT', 66.68, 5.54, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89524, 'COPO CP440T/ABNT 1000UC', 'CP440T/ABNT', 50.7, 5.54, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89532, 'COPO CP500B/ABNT 1000UC', 'CP500B/ABNT', 62.63, 6.3, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89540, 'COPO CP500T/ABNT 1000UC', 'CP500T/ABNT', 56.49, 6.3, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89559, 'COPO CP550T/ABNT 900UC', 'CP550T/ABNT', 58.62, 6.24, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89575, 'COPO CP250T/ABNT 1000UC (TULIPA)', 'CP250T/ABNT', 44, 2.75, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89745, 'COPO CP200BI/ABNT/L C.DE BONECA V.PAPER', 'CP200BI/ABNT/L', 108, 6.6, 
    '2005-08-30');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89885, 'COPO CB110ABNT 3000UC', 'CB110ABNT', 54.89, 5.7, 
    '2005-08-31');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (90824, 'COPO CP300B/ABNT/FMT 2000UC FORMATTO', 'CP300B/ABNT/FMT', 84.98, 6.6, 
    '2005-09-27');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (90832, 'COPO CP400B/ABNT/ARO 1000UC ARO', 'CP400B/ABNT/ARO', 78.38, 5, 
    '2005-09-27');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (90840, 'COPO CP440T/ABNT/ARO 1000UC ARO', 'CP440T/ABNT/ARO', 97.3, 5.54, 
    '2005-09-27');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (90859, 'COPO CP330T/ABNT/ARO 1000UC ARO', 'CP330T/ABNT/ARO', 48.47, 3.63, 
    '2005-09-27');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (91251, 'POTE PP160TI000 BIG BOM COLEGIAL DUENDES', 'PP160TI000', 79, 5, 
    '2005-10-10');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (91502, 'POTE PP500BI000 TEM.NAPANELA SEM PIMENTA', 'PP500BI000', 166, 13.5, 
    '2005-10-17');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (91510, 'COPO CP330TI002 2000UC FAST SHAKE', 'CP330TI002', 114.66, 8, 
    '2005-10-17');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (91545, 'TAMPA TP75BL001 1000UC', 'TP75BL001', 37.74, 2, 
    '2005-10-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (91553, 'TAMPA TP75TL001 1000UC', 'TP75TL001', 47.7, 2, 
    '2005-10-18');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (91952, 'COPO CP330BI000/1CC 2000UC  HABIBS', 'CP330BI000/1CC', 105, 10, 
    '2005-10-28');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (92568, 'PRATO PF260/4 250UC', 'PF260/4', 39, 3.5, 
    '2005-11-21');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (92789, 'COPO CP330TI002 2000UC CHOPP HABIBS', 'CP330TI002', 105, 8, 
    '2005-11-24');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (92916, 'TAMPA TT79/1 2000UC TRANSP SEM FURO', 'TT79/1', 58.44, 2.8, 
    '2005-11-28');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (94374, 'COPO CP330TL003/1 1000UC - ABNT', 'CP330TL003/1', 44, 3.63, 
    '2006-01-24');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (95141, 'POTE PP340TI000/1 IMEC 2006 C/MANGAS', 'PP340TI000/1', 121, 7.5, 
    '2006-03-06');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (95168, 'BANDEJA B01/1 500UC', 'B01/1', 98.63, 5.5, 
    '2006-03-06');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (96687, 'COPO CP550TI000 900UC MARIETTA 2006', 'CP550TI000', 66.15, 6.75, 
    '2006-05-15');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (97152, 'COPO CB80ES/ABNT 2500UC', 'CB80ES/ABNT', 37.5, 3.5, 
    '2006-06-19');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (97160, 'COPO C80CRES/ABNT 2500UC', 'C80CRES/ABNT', 58.97, 3.5, 
    '2006-06-19');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (97594, 'POTE PP500BI003/1 SARAMEL NAPOLITANO', 'PP500BI003/1', 121.71, 7.5, 
    '2006-07-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (98701, 'POTE PP120TI000/1 REFRESKATA CREME 2010', 'PP120TI000/1', 107, 5.2, 
    '2006-09-26');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (98710, 'POTE PP120TI000/1 REFRESKATA CHOCOL.2010', 'PP120TI000/1', 107, 5.2, 
    '2006-09-26');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (98779, 'COPO CP200T/ABNT/ARO 3000UC', 'CP200T/ABNT/ARO', 88.12, 6.6, 
    '2006-09-27');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (98787, 'COPO CP500B/ABNT/ARO 1000UC', 'CP500B/ABNT/ARO', 101.88, 6.3, 
    '2006-09-27');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (98795, 'COPO CP550T/ABNT/ARO 900UC', 'CP550T/ABNT/ARO', 103.37, 6.24, 
    '2006-09-27');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (477, 'TAMPA TS55ES_01 1000UC', 'TS55ES_01', 33.6, 1.65, 
    '2006-11-22');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (590, 'TAMPA TS55ESF_01 1000UC', 'TS55ESF_01', 31.93, 1.65, 
    '2006-11-22');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (841, 'TAMPA TS55F_01 900UC', 'TS55F_01', 28.74, 1.49, 
    '2006-11-22');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (2399, 'TAMPA TS55TEF_01 1000UC TRANSP. FURADA', 'TS55TEF_01', 58.5, 1.65, 
    '2006-11-22');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (2402, 'TAMPA TS55TF_01 900UC TRANSPARENTE FURAD', 'TS55TF_01', 30.53, 1.49, 
    '2006-11-22');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (3034, 'POTE PB250PI001/1  DANIONELLE 2006', 'PB250PI001/1', 82.4, 4.8, 
    '2006-12-08');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (13749, 'COPO CP200BI/ABNT/L 3000UC MAIS SABOR', 'CP200BI/ABNT/L', 100.11, 6.6, 
    '2008-06-12');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (13757, 'COPO CP200TI/ABNT/L 3000UC TAMPICO', 'CP200TI/ABNT/L', 100.11, 6.6, 
    '2008-06-13');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (13854, 'POTE PP160TI000 KUKA FRIA MIX/ MORANGO', 'PP160TI000', 79.5, 5, 
    '2008-06-20');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (16454, 'COPO CP330BI004 1000UC  DINOS', 'CP330BI004', 72.6, 4, 
    '2008-09-04');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (17965, 'CP200BI/ABNT/L PALHACO 2010 ULTRAFEST', 'CP200BI/ABNT/L', 108, 6.6, 
    '2008-09-12');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (21750, 'COPO CP440TI/ABNT 1000UC WUNDER BIER', 'CP440TI/ABNT', 67.08, 5.54, 
    '2008-09-29');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (42862, 'COPO CP550TI000 MILKSHAKE PADRAO DZT', 'CP550TI000', 104.5, 6.75, 
    '2008-12-03');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (42986, 'COPO CP330TI001 MILKSHAKE PADRAO DZT', 'CP330TI001', 57, 4, 
    '2008-12-03');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (84360, 'POTE PP160TI000/1 ICE`N`UP SUNDAE', 'PP160TI000/1', 75.6, 4, 
    '2005-03-15');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (47414, 'COPO CP200CL/ABNT 2500UC', 'CP200CL/ABNT', 51.1, 5.5, 
    '2009-01-14');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (48208, 'POTE PP450BI000/1 1000UC TEMPERITO', 'PP450BI000/1', 157.5, 10, 
    '2009-01-29');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (140, 'COPO CP550TI000 SUCO BAGACO BIFASICO', 'CP550TI000', 104.7, 6.75, 
    '2009-02-12');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (20613, 'POTE PP300BI001/3 REFRESKATA NAPOLIATANO', 'PP300BI001/3', 113, 6.5, 
    '2010-09-06');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (20630, 'COPO CP440TI/ABNT WUNDER BIER 2011', 'CP440TI/ABNT', 67.08, 5.54, 
    '2010-09-08');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (20729, 'COPO CP330BI003 2000UC PIZZA SET', 'CP330BI003', 114, 8, 
    '2010-09-08');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (10804, 'POTE PP340BI000/2 1000UC URCA VERMELHO', 'PP340BI000/2', 105, 6.5, 
    '2007-12-19');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (20737, 'COPO CP330BI004 1000UC DIVINA GULA', 'CP330BI004', 65, 4, 
    '2010-09-09');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (20753, 'COPO CP330BI003 TENTACAO DO MATE YOGULOS', 'CP330BI003', 140.45, 8, 
    '2010-09-09');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (20800, 'COPO CP550BI000 TENTACAO DO MATE YOGULOS', 'CP550BI000', 118.5, 6.75, 
    '2010-09-09');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (8230, 'COPO CP550BI000CC COCA-COLA PADRAO', 'CP550BI000CC', 83.17, 6.75, 
    '2007-09-12');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (20834, 'POTE PP300BI001/3 URQUINHA SORVETES 6.5', 'PP300BI001/3', 113, 6.5, 
    '2010-09-09');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (10626, 'COPO CB80IM/3 2500UC APTI 2007', 'CB80IM/3', 90.16, 3.5, 
    '2007-12-13');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (20842, 'COPO CP550BI000 900UC ACADEMIA DO ACAI', 'CP550BI000', 107, 6.75, 
    '2010-09-13');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (98728, 'POTE PP120TI000/1 REFRESKATA MORAN.2010', 'PP120TI000/1', 107, 5.2, 
    '2006-09-26');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (21601, 'COPO CP440BI/ABNT WUNDER BIER 2010', 'CP440BI/ABNT', 67.08, 5.54, 
    '2010-11-03');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (19100, 'COPO CP550BI000 COCA-COLA PETISKEIRA', 'CP550BI000', 83.17, 6.75, 
    '2010-07-13');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (87351, 'COPO CP200BI/ABNT/L 1 ANINHO AZUL BF', 'CP200BI/ABNT/L', 105, 6.6, 
    '2005-07-06');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89214, 'PRATO PR180/2 1000UC', 'PR180/2', 50, 4, 
    '2005-08-23');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89230, 'PRATO PR260/3 250UC', 'PR260/3', 40.45, 3.25, 
    '2005-08-23');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (89435, 'COPO CP180TES/ABNT 2500UC LINHA OURO', 'CP180TES/ABNT', 47.73, 4.95, 
    '2005-08-25');
Insert into produtos
   (cd_produto, nm_produto, id_referencia, vl_unitario, ps_unitario, 
    dt_cadastro)
 Values
   (2194, 'TAMPA TS55TE_01 1000UC', 'TS55TE_01', 34.43, 1.65, 
    '2006-11-22');