/*
cidades de SC
*/
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200051,'Abdon Batista','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200101,'Abelardo Luz','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200200,'Agrolândia','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200309,'Agronômica','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200408,'Água Doce','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200507,'Águas de Chapecó','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200556,'Águas Frias','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200606,'Águas Mornas','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200705,'Alfredo Wagner','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200754,'Alto Bela Vista','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200804,'Anchieta','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4200903,'Angelina','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201000,'Anita Garibaldi','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201109,'Anitápolis','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201208,'Antônio Carlos','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201257,'Apiúna','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201273,'Arabutã','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201307,'Araquari','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201406,'Araranguá','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201505,'Armazém','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201604,'Arroio Trinta','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201653,'Arvoredo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201703,'Ascurra','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201802,'Atalanta','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201901,'Aurora','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4201950,'Balneário Arroio do Silva','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202008,'Balneário Camboriú','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202057,'Balneário Barra do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202073,'Balneário Gaivota','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202081,'Bandeirante','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202099,'Barra Bonita','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202107,'Barra Velha','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202131,'Bela Vista do Toldo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202156,'Belmonte','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202206,'Benedito Novo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202305,'Biguaçu','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202404,'Blumenau','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202438,'Bocaina do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202453,'Bombinhas','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202503,'Bom Jardim da Serra','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202537,'Bom Jesus','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202578,'Bom Jesus do Oeste','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202602,'Bom Retiro','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202701,'Botuverá','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202800,'Braço do Norte','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202859,'Braço do Trombudo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202875,'Brunópolis','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4202909,'Brusque','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203006,'Caçador','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203105,'Caibi','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203154,'Calmon','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203204,'Camboriú','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203253,'Capão Alto','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203303,'Campo Alegre','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203402,'Campo Belo do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203501,'Campo Erê','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203600,'Campos Novos','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203709,'Canelinha','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203808,'Canoinhas','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203907,'Capinzal','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4203956,'Capivari de Baixo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204004,'Catanduvas','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204103,'Caxambu do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204152,'Celso Ramos','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204178,'Cerro Negro','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204194,'Chapadão do Lageado','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204202,'Chapecó','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204251,'Cocal do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204301,'Concórdia','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204350,'Cordilheira Alta','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204400,'Coronel Freitas','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204459,'Coronel Martins','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204509,'Corupá','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204558,'Correia Pinto','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204608,'Criciúma','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204707,'Cunha Porã','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204756,'Cunhataí','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204806,'Curitibanos','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4204905,'Descanso','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205001,'Dionísio Cerqueira','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205100,'Dona Emma','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205159,'Doutor Pedrinho','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205175,'Entre Rios','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205191,'Ermo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205209,'Erval Velho','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205308,'Faxinal dos Guedes','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205357,'Flor do Sertão','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205407,'Florianópolis','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205431,'Formosa do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205456,'Forquilhinha','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205506,'Fraiburgo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205555,'Frei Rogério','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205605,'Galvão','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205704,'Garopaba','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205803,'Garuva','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4205902,'Gaspar','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206009,'Governador Celso Ramos','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206108,'Grão-Pará','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206207,'Gravatal','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206306,'Guabiruba','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206405,'Guaraciaba','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206504,'Guaramirim','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206603,'Guarujá do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206652,'Guatambú','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206702,'Herval d\'Oeste','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206751,'Ibiam','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206801,'Ibicaré','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4206900,'Ibirama','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207007,'Içara','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207106,'Ilhota','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207205,'Imaruí','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207304,'Imbituba','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207403,'Imbuia','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207502,'Indaial','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207577,'Iomerê','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207601,'Ipira','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207650,'Iporã do Oeste','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207684,'Ipuaçu','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207700,'Ipumirim','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207759,'Iraceminha','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207809,'Irani','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207858,'Irati','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4207908,'Irineópolis','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208005,'Itá','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208104,'Itaiópolis','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208203,'Itajaí','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208302,'Itapema','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208401,'Itapiranga','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208450,'Itapoá','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208500,'Ituporanga','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208609,'Jaborá','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208708,'Jacinto Machado','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208807,'Jaguaruna','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208906,'Jaraguá do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4208955,'Jardinópolis','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209003,'Joaçaba','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209102,'Joinville','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209151,'José Boiteux','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209177,'Jupiá','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209201,'Lacerdópolis','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209300,'Lages','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209409,'Laguna','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209458,'Lajeado Grande','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209508,'Laurentino','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209607,'Lauro Müller','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209706,'Lebon Régis','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209805,'Leoberto Leal','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209854,'Lindóia do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4209904,'Lontras','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210001,'Luiz Alves','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210035,'Luzerna','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210050,'Macieira','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210100,'Mafra','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210209,'Major Gercino','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210308,'Major Vieira','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210407,'Maracajá','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210506,'Maravilha','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210555,'Marema','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210605,'Massaranduba','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210704,'Matos Costa','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210803,'Meleiro','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210852,'Mirim Doce','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4210902,'Modelo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211009,'Mondaí','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211058,'Monte Carlo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211108,'Monte Castelo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211207,'Morro da Fumaça','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211256,'Morro Grande','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211306,'Navegantes','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211405,'Nova Erechim','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211454,'Nova Itaberaba','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211504,'Nova Trento','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211603,'Nova Veneza','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211652,'Novo Horizonte','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211702,'Orleans','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211751,'Otacílio Costa','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211801,'Ouro','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211850,'Ouro Verde','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211876,'Paial','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211892,'Painel','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4211900,'Palhoça','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212007,'Palma Sola','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212056,'Palmeira','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212106,'Palmitos','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212205,'Papanduva','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212239,'Paraíso','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212254,'Passo de Torres','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212270,'Passos Maia','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212304,'Paulo Lopes','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212403,'Pedras Grandes','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212502,'Penha','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212601,'Peritiba','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212650,'Pescaria Brava','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212700,'Petrolândia','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212809,'Balneário Piçarras','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4212908,'Pinhalzinho','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213005,'Pinheiro Preto','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213104,'Piratuba','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213153,'Planalto Alegre','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213203,'Pomerode','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213302,'Ponte Alta','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213351,'Ponte Alta do Norte','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213401,'Ponte Serrada','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213500,'Porto Belo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213609,'Porto União','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213708,'Pouso Redondo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213807,'Praia Grande','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4213906,'Presidente Castello Branco','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214003,'Presidente Getúlio','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214102,'Presidente Nereu','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214151,'Princesa','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214201,'Quilombo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214300,'Rancho Queimado','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214409,'Rio das Antas','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214508,'Rio do Campo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214607,'Rio do Oeste','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214706,'Rio dos Cedros','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214805,'Rio do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4214904,'Rio Fortuna','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215000,'Rio Negrinho','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215059,'Rio Rufino','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215075,'Riqueza','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215109,'Rodeio','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215208,'Romelândia','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215307,'Salete','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215356,'Saltinho','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215406,'Salto Veloso','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215455,'Sangão','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215505,'Santa Cecília','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215554,'Santa Helena','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215604,'Santa Rosa de Lima','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215653,'Santa Rosa do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215679,'Santa Terezinha','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215687,'Santa Terezinha do Progresso','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215695,'Santiago do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215703,'Santo Amaro da Imperatriz','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215752,'São Bernardino','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215802,'São Bento do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4215901,'São Bonifácio','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216008,'São Carlos','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216057,'São Cristóvão do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216107,'São Domingos','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216206,'São Francisco do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216255,'São João do Oeste','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216305,'São João Batista','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216354,'São João do Itaperiú','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216404,'São João do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216503,'São Joaquim','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216602,'São José','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216701,'São José do Cedro','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216800,'São José do Cerrito','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4216909,'São Lourenço do Oeste','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217006,'São Ludgero','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217105,'São Martinho','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217154,'São Miguel da Boa Vista','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217204,'São Miguel do Oeste','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217253,'São Pedro de Alcântara','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217303,'Saudades','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217402,'Schroeder','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217501,'Seara','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217550,'Serra Alta','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217600,'Siderópolis','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217709,'Sombrio','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217758,'Sul Brasil','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217808,'Taió','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217907,'Tangará','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4217956,'Tigrinhos','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218004,'Tijucas','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218103,'Timbé do Sul','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218202,'Timbó','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218251,'Timbó Grande','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218301,'Três Barras','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218350,'Treviso','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218400,'Treze de Maio','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218509,'Treze Tílias','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218608,'Trombudo Central','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218707,'Tubarão','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218756,'Tunápolis','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218806,'Turvo','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218855,'União do Oeste','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218905,'Urubici','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4218954,'Urupema','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219002,'Urussanga','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219101,'Vargeão','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219150,'Vargem','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219176,'Vargem Bonita','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219200,'Vidal Ramos','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219309,'Videira','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219358,'Vitor Meireles','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219408,'Witmarsum','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219507,'Xanxerê','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219606,'Xavantina','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219705,'Xaxim','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4219853,'Zortéa','SC');
INSERT INTO `cidade` (`id`,`nome`,`uf`) VALUES (4220000,'Balneário Rincão','SC');
