/*
-- Query: SELECT * FROM bd_emprego.vaga
-- Date: 2023-11-09 14:17
*/
INSERT INTO `vaga` (`id`,`nome`,`descricao`,`data_cadastro`,`qtde`,`status`,`valor_salario_inicial`,`valor_salario_final`,`id_empresa`,`id_area_atuacao`) VALUES (1,'Assistente de Vendas','Emitir e/ou liberar pedidos de venda. Gerenciar pedidos de venda, com foco no atendimento da expectativa do cliente. Emissões de relatórios da carteira de pedidos, para envio aos clientes. Atendimento a clientes e representantes. Dar suporte aos exec','2023-11-09 00:00:00',2,'R',2000.00,2500.00,1,1);
INSERT INTO `vaga` (`id`,`nome`,`descricao`,`data_cadastro`,`qtde`,`status`,`valor_salario_inicial`,`valor_salario_final`,`id_empresa`,`id_area_atuacao`) VALUES (2,'Auxiliar de Marketing Digital','Acompanhar a execução do plano de marketing e calendário comercial. Acompanhar e atualizar dados em planilhas de controle do setor de marketing. Auxiliar na realização de pesquisas de mercado e tendências. Auxiliar no contato entre a empresa e agênci','2023-11-08 00:00:00',1,'S',2500.00,3000.00,1,2);
INSERT INTO `vaga` (`id`,`nome`,`descricao`,`data_cadastro`,`qtde`,`status`,`valor_salario_inicial`,`valor_salario_final`,`id_empresa`,`id_area_atuacao`) VALUES (3,'CONSULTOR TÉCNICO/DESENVOLVIMENTO','Como Consultor Técnico/Desenvolvimento, você será parte essencial da equipe, envolvido em desafios e projetos inovadores.','2023-11-08 00:00:00',1,'R',3500.00,4000.00,2,3);
INSERT INTO `vaga` (`id`,`nome`,`descricao`,`data_cadastro`,`qtde`,`status`,`valor_salario_inicial`,`valor_salario_final`,`id_empresa`,`id_area_atuacao`) VALUES (4,'VENDEDOR (VEÍCULOS)','Atendimento ao cliente do início da recepção até a finalização contratual','2023-11-09 00:00:00',2,'R',1700.00,12000.00,3,1);
INSERT INTO `vaga` (`id`,`nome`,`descricao`,`data_cadastro`,`qtde`,`status`,`valor_salario_inicial`,`valor_salario_final`,`id_empresa`,`id_area_atuacao`) VALUES (5,'DESIGNER','Tenha intuição criativa;','2023-11-07 00:00:00',1,'R',2000.00,3000.00,2,2);
INSERT INTO `vaga` (`id`,`nome`,`descricao`,`data_cadastro`,`qtde`,`status`,`valor_salario_inicial`,`valor_salario_final`,`id_empresa`,`id_area_atuacao`) VALUES (6,'Operador de Sistema','Entender de informática e monitoramento;','2023-11-06 00:00:00',2,'S',2500.00,3500.00,3,3);
INSERT INTO `vaga` (`id`,`nome`,`descricao`,`data_cadastro`,`qtde`,`status`,`valor_salario_inicial`,`valor_salario_final`,`id_empresa`,`id_area_atuacao`) VALUES (7,'Desenvolvedor Delphi Pleno','Desenvolver soluções ERP nas linguagens Delphi Rio e SQL (Firebird).','2023-11-05 00:00:00',3,'R',4000.00,6000.00,3,3);
