Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (250791, 'CANGURU S.A.IND.COM.PRODUTOS PLASTICOS', 'CRICIUMA', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (289582, 'ASSOCIACAO DO SHOPPING ARAVEST', 'ARARANGUA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (233170, 'ALEGRIA E FESTA COM.ARTIG.FESTA ENCARTEL', 'CASCAVEL', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (251976, 'RESI-SACO MANUTEC COMERCIAL LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (46744, 'EMBALAGENS ALFENENSE LTDA.', 'ALFENAS', 698);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (280585, 'TAVARES SILVA & SILVA LTDA', 'GOIANIA', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (267708, 'RA CATERING LTDA', 'GUARULHOS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (218499, 'ICE_N_UP IND.COM.& DISTRIB.LTDA', 'OURO FINO', 698);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (264555, 'LIMPAPEL RJ COMERCIO DE PAPEIS LTDA', 'BARRA MANSA', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (109428, 'NERTEX IND.COM.E REPRESENTACOES LTDA.', 'GUABIRUBA', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (261580, 'W.S FERREIRA COM. DE PROD.DESC. LTDA ME', 'BAURU', 1414);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (271411, 'MAKRO ATACADISTA S/A', 'ARACATUBA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (50407, 'MAKRO ATACADISTA S.A.', 'RIBEIRAO PRETO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (250627, 'MAKRO ATACADISTA S.A.', 'MANAUS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (283630, 'MAKRO ATACADISTA S/A', 'SANTOS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (65501, 'NEUSIMAR TEODORA DA SILVA RIOS', 'CATALAO', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (278580, 'IRMAOS ANDREAZZA LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (128554, 'TOC FRIO SORVETES LTDA.ME.', 'ITAUNA', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (8303, 'SHIMAPEL COM.REPRES.LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (15946, 'LOJAS AMERICANAS S.A.', 'BARUERI', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (127116, 'LOSEL EMBALAGENS E PRESENTES LTDA.', 'ARACAJU', 1651);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (15482, 'JORI ARTEFATOS DE PAPEL LTDA-EPP', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (286311, 'CARTORIO DE REGISTRO DE IMOVEIS', 'ICARA', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (268313, 'A.ANGELONI & CIA.LTDA. - CD', 'PORTO BELO', 1457);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (229903, 'SORVETERIA VITORIA LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (1902, 'DISTR.DE DOCES SILVA LTDA.', 'CONSELHEIRO LAFAIETE', 604);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (254096, 'ALEGRO EMB. E ARTIGOS PARA FESTAS LTDA.', 'VERANOPOLIS', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (222895, 'COMERCIAL VIGOR LTDA', 'BALNEARIO GAIVOTA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (290181, 'CARLINE GUEDES DE ALMEIDA - ME', 'PALHOCA', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (218464, 'ALIBABA COM.DE REFEICOES LTDA-ME', 'FLORIANOPOLIS', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (147206, 'FERON E TERRA LTDA.', 'SAO LUIZ GONZAGA', 752);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (259616, 'JOVINC EMBALAGENS DESCARTAVEIS LTDA.ME.', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (25364, 'S.M.COML.E DIST.LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (181021, 'LUCIANA APARECIDA CORREA', 'MURIAE', 604);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (6220, 'BEIJAMIN GARCIA DE MELO', 'PALMEIRAS DE GOIAS', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (133825, 'J.A.EMBALAGENS MINEIRINHA LTDA.', 'PASSOS', 698);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (280232, 'K D LIMA RESTAURANTE LTDA', 'SAO LUIS', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (160881, 'RESTAURANTE MEDEIROS LTDA.', 'FLORIANOPOLIS', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (288098, 'BRUMA RESTAURANTE E LANCHONETE LTDA - EP', 'SAO JOSE', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (179183, 'MAKRO ATACADISTA S.A.', 'CAXIAS DO SUL', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (250813, 'MARIMEL DIST.DE PRODUTOS ALIMT.LTDA.', 'MARINGA', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (259950, 'MILKTALI COMERCIO DE SORVETES LTDA ME', 'JANDAIA DO SUL', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (233277, 'TVG COM.PEC.REFRIG.LTDA.', 'MAL CANDIDO RONDON', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (73210, 'TELO E MENEZES DIST.LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (179876, 'DOCE FESTAS BARRUSSI LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (161802, 'RR EMBALAGENS LTDA', 'BOA ESPERANCA', 698);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (282880, 'DISTRIBUIDORA DE ALIMENTOS XIMENDES LTDA', 'BRASILIA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (243728, 'SG SORVETES LTDA.', 'ICARA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (255696, 'SOUSA COM DE ART PARA FESTAS E CONFECCOE', 'ARAGUARI', 337);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (77119, 'MASSAIOLA IND.E COM.DE MASSAS LTDA.', 'FLORES DA CUNHA', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (269999, 'FLOOR COM.DE PROD.EQUIP.P/HIG.PROFIS.LTD', 'RIBEIRAO PRETO', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (290386, ' ELOISE HIGUTSI KOMESU-ME', 'PRESIDENTE PRUDENTE', 1414);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (148636, 'BRASIPEL ARTIGOS P/FESTAS LTDA-ME', 'SANTO ANDRE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (288756, 'CLEAN-MIX PROD. DE HIG. E LIMP. LTDA-ME', 'VOLTA REDONDA', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (140678, 'CSS DISTRIBUIDORA LTDA.', 'BLUMENAU', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (86495, 'DISTRIBUIDORA ROBERTO COM.E REPRES.LTDA.', 'ITAJAI', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (85367, 'DELAZZERI EMBALAGENS LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (123080, 'INDUSTRIAS MIRIAN LTDA.', 'SERAFINA CORREA', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (50440, 'MAKRO ATACADISTA S.A.', 'SAO GONCALO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (50423, 'MAKRO ATACADISTA S.A.', 'BAURU', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (50415, 'MAKRO ATACADISTA S.A.', 'S JOSE DO RIO PRETO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (18058, 'MAKRO ATACADISTA S.A.', 'FORTALEZA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (280321, 'MAKRO ATACADISTA S/A', 'MARILIA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (210870, 'MAKRO ATACADISTA S.A.', 'BELO HORIZONTE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41149, 'MAKRO ATACADISTA S.A.', 'S BERNARDO DO CAMPO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (194786, 'DISTRIBUIDORA DE DOCES FLOR DE LIMA LTDA', 'S BERNARDO DO CAMPO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (190659, 'MAKRO ATACADISTA S.A.', 'ARACAJU', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (44296, 'HELIO FERNANDES DA SILVA', 'CERES', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (247120, 'UNIFRIOS E EMBALAGENS LTDA.', 'GOIANIA', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (142484, 'BAZAR GURI LTDA', 'FORMIGA', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (106534, 'LIVRARIA E PAPELARIA ITAPOA LTDA.', 'SAO JOSE DOS CAMPOS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (272752, 'ROSIMEIRE BERNARDES DE OLIVEIRA  ME', 'LENCOIS PAULISTA', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (241849, 'RHAFAEL RUSSI DE SOUZA ME.', 'BALNEARIO CAMBORIU', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (281611, 'SAO LUIS NUTRICAO LTDA-ME', 'SALVADOR', 183);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (154172, 'G.F AUTO ATACADO LTDA', 'TRES CORACOES', 698);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (178926, 'KAWIN SORVETES LTDA.ME.', 'SAMAMBAIA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (261165, 'COM.DE PLASTICOS E EMB. SAO LUIZ LTDA.', 'CURITIBA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (282529, 'KELLY CRISTINA MONDEJA - ME', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (262889, 'IRMAOS BRETAS, FILHOS & CIA.LTDA.', 'RIBEIRAO DAS NEVES', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (229822, 'C.G.COMERCIO DE PRODUTOS DE LIMPEZA-EPP.', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (56103, 'MERCADO PAULINE LTDA.', 'MORRO DA FUMACA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (280577, 'BRUMISNKI SUCOS E ALIMENTOS LTDA - EPP', 'OSASCO', 1414);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (92940, 'A.MUNDSTOCK ME', 'SANTA CRUZ DO SUL', 892);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (68381, 'CDBU DISTR.DE BRINQUEDOS E UTILID.LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (288535, 'MERCEARIA LOTTE LTDA-EPP', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (279358, 'C.C.B DA SILVA-ROCHA DIST.DE ALIM.LTDA.M', 'RECANTO DAS EMAS', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (244422, 'SORVETES PINK LTDA ME', 'CHAPECO', 1864);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (56243, 'E.T.REPRESENTACOES COMERCIAIS LTDA - EPP', 'VALINHOS', 914);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (277428, 'JAQUELINE ANTONIO NIENKOTTER - ME', 'SAO JOSE', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (281662, 'DELFINO LOPES DE OLIVEIRA', 'BARRA BONITA', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (229105, 'PEDRO MUFFATO E CIA.LTDA.', 'IBIPORA', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (272558, 'R L B DE QUEIROZ FILHO ME.', 'FORTALEZA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (200433, 'CANDY DISTRIBUIDORA DE DOCES LTDA-EPP', 'CURITIBA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (192724, 'NOVA LIMP DISTR.DE EMB.E DESCART.TDA', 'SANTO ANDRE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (268119, 'UNIMED CRICIUMA COOP TRAB MED REG CARBON', 'CRICIUMA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (32611, 'CARAMUJO DIST.DE EMBALAGENS LTDA-ME', 'BRASILIA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (243906, 'PAMPLONA ALIMENTOS S.A', 'RIO DO SUL', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (200565, 'JORGE HENRIQUE CURY FORTES', 'CURITIBA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (82970, 'CENTRO DE COMPRAS ZALESKI LTDA', 'HORIZONTINA', 752);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (125768, 'RIOMED DISTRIBUICAO LTDA', 'RIO DO SUL', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (5002, 'CEREALISTA OLIVEIRA LTDA.', 'ALVORADA', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (289493, 'FRUIT COM. VAREJ. DE SUCOS LTDA EPP', 'GUARATINGUETA', 1414);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (271403, 'MAKRO ATACADISTA S/A', 'CAMPINA GRANDE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (167797, 'MAKRO ATACADISTA S.A.', 'MANAUS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (233196, 'MAKRO ATACADISTA S.A.', 'RIO DE JANEIRO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41092, 'MAKRO ATACADISTA S.A.', 'PORTO ALEGRE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (261939, 'ANTONIO CARLOS FERREIRA DA SILVA - ME', 'RIO VERDE', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (282120, 'MARTIN-BROWER FOOD S.C.TRANSP. SERV.LTDA', 'SAO PAULO', 914);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (51063, 'LUCIANO PREISSER ME.', 'SETE LAGOAS', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (252573, 'AROLDO S.D.LARA', 'BELO HORIZONTE', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (236446, 'MACOVIL COMERCIAL LTDA.', 'BELO HORIZONTE', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (191957, 'SORVETERIA NOSSA SENHORA DE LOURDES LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (118630, 'COML.GEPLASTICOS LTDA.', 'VARGINHA', 698);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (70530, 'A.G.B.ACOUGUE E MERC.LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (279773, 'SS COM.PROD.P/SORVETERIA LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (208434, 'ALMIR SIGNOLFI ME.', 'APUCARANA', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (227684, 'LUNAPEL EMBALAGENS E DESCARTAVEIS LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (271110, 'PAULO CESAR DRAGUETTI', 'LAJEADO', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (64220, 'MENOTI COM.E REPRESENTACOES LTDA', 'SANTA MARIA', 892);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (84700, 'VONPAR REFRESCOS S/A', 'FARROUPILHA', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (76805, 'VONPAR REFRESCOS S/A FILIAL', 'PELOTAS', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (186589, 'PATURI COMERCIO DE FRIOS LTDA ME', 'BRAZLANDIA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (142883, 'LIMPE CALL COMERCIAL LTDA - ME.', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (216100, 'APTI ALIM.LTDA.', 'CHAPECO', 1864);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (170267, 'EMBALIX COM.EMBALAGENS E PROD. PARA LIMP', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (270849, 'RODOSNACK TURMALINA LANC E REST LTDA', 'CORDEIROPOLIS', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (92827, 'EMBALAGENS VALVERDE LTDA ME', 'MURIAE', 604);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (289965, 'CASA DAS EMBALAGENS LUPEL LTDA-ME.', 'ARACUAI', 604);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (283428, 'RV FOODS ALIMENTOS LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (14010, 'MAURILIO MARIN E CIA.LTDA.', 'LAGES', 1864);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (116815, 'MAKRO ATACADISTA S.A.', 'CAMBE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (227870, 'RESTAURANTE HO CHI MINH LTDA.ME.', 'MARILIA', 1716);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (63665, 'SUPERMERCADO CONDOR LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (239356, 'MATE AVENIDA 50 CAFE E LANCHES LTDA.', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (57886, 'DISTRIBUIDORA COMERCIAL REMBRAZ LTDA', 'MANAUS', 566);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (120561, 'SUPERMERCADO CHIBANA LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (228540, 'CASA DO SACO MATERIAIS DE LIMPEZA LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (115843, 'D.Z.L.DIST.ZANATTA LTDA.', 'PORTO ALEGRE', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (990990, 'CANGURU S.A.IND.COM.PRODUTOS PLASTICOS', 'CRICIUMA', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (273015, 'AB LIMP COMERCIO E REPRESENTACAO LTDA.', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (182974, 'CENTRAL DO LIBANO COM. DE DESC. LTDA EP', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (221716, 'M.L.BERNARDI & CIA.LTDA-ME', 'CURITIBA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (244430, 'J A MATOZO COM. PROD. LIMP. LTDA', 'SAO JOSE DOS PINHAIS', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (284327, 'TERESINHA LEITE DE CARVALHO', 'CARAZINHO', 752);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (173070, 'PLAST-FORT COM.DE EMBALAGENS LTDA-ME.', 'LONDRINA', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (273147, 'MAKRO ATACADISTA S/A', 'PORTO VELHO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (179353, 'MAKRO ATACADISTA S.A.', 'GUARULHOS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41122, 'MAKRO ATACADISTA S.A.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (54780, 'MAKRO ATACADISTA S.A.', 'SALVADOR', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (202886, 'MAKRO ATACADISTA S.A.', 'CURITIBA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (52329, 'MAKRO ATACADISTA S.A.', 'SALVADOR', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (50377, 'MAKRO ATACADISTA S.A.', 'SERRA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (202967, 'DISTRIBUIDORA DE DOCES SAO JOAO LTDA', 'CONSELHEIRO LAFAIETE', 604);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (278599, 'IRMAOS ANDREAZZA LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (272264, 'HIGIENIZA COM DE DESCARTAVEIS LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (117960, 'INCORPOL IND.E COMER.PROD.DE LIMP.LTDA.', 'CORDEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (273791, 'CAFE E BAR RIO ARDA LTDA.', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (283193, 'FONTE DISTRIBUIDORA LTDA', 'GOIANIA', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (247545, 'COLOR CONCEPTS IND.COM.EMBALAGENS LTDA.', 'VALINHOS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (99244, 'BIG BOM SORVETES LTDA.ME.', 'ARARANGUA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (257737, 'ROSA RUSSI DE SOUZA ME.', 'ITAJAI', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (184721, 'RG DISTIBUIDORA DE PRODUTOS ALIME LTDA.', 'TAGUATINGA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (282634, 'JORI - PAPEL COMERCIO DE DESCARTAVEIS LT', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (212628, 'COMERCIAL POLIPLAS DE LEOPOLDINA LTDA', 'LEOPOLDINA', 604);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (273759, 'JULICA MATERIAL E PROD.PRO LAR LTDA-EPP.', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (143847, 'EMBRULHE EMBALAGENS BRUSQUE LTDA.', 'BRUSQUE', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (66176, 'WEINERT E CIA LTDA', 'SANTO ANGELO', 752);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (121703, 'D.LIMP COM.LTDA.ME.', 'DUQUE DE CAXIAS', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (151246, 'DISTRIBUIDORA O REITOR LTDA.ME.', 'SAQUAREMA', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (166693, 'PONTILHAO ART.P/ SORVETERIA E CONF.LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (181102, 'IDEAL ABASTECEDORA DE EMBALAGENS LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (279862, 'MARIA RAVANELI NUNES ZAKIR', 'MACATUBA', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (126608, 'KADINI E KADINI LTDA.', 'TAPEJARA', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (176877, 'DO-SUL COMERCIO DE BEBIDAS LTDA', 'VERANOPOLIS', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (147982, 'VONPAR REFRESCOS S.A.', 'PORTO ALEGRE', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (63517, 'SUPRICORP SUPRIMENTOS LTDA.', 'BARUERI', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (282898, 'KPMIX COMERCIAL LTDA-ME', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (159387, 'KUERTEN DIST.DE PRODUTOS DE LIMPEZA LTDA', 'SAO JOSE', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (195863, 'NAIDES LUCIA SEMINOTTI OLIVEIRA ME', 'SAO JOSE', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (25933, 'B.V.COM. DE DOCES LTDA', 'LONDRINA', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (27880, 'ROTISSERIA SIRIO LIBANEZA LTDA.', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (274186, 'U.K- PIZZA PASTA LTDA.', 'SAO PAULO', 1414);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (249076, 'B.E.L.C. COM. DE EMB. E DESC. LTDA', 'VALINHOS', 914);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (100293, 'FUNDACAO UNIV.DE CAXIAS DO SUL', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (117552, 'DISTRIBUIDORA DE DOCES TIQUINHO LTDA.', 'SAO CARLOS', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (266230, 'JOHNSON & JOHNSON BRASIL IND.COM.PROD. S', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (280267, 'COUTO & BARROS COMERCIAL LTDA', 'ALFENAS', 698);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (279420, 'PARK BLUMENAU RESTAURANTE LTDA - ME', 'BLUMENAU', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (19348, 'CASA D_AGUA MATS.CONSTR.LTDA', 'SAO JOSE', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (289515, 'CONSORCIO INTERPAR', 'ARAUCARIA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (232653, 'B.C COMERCIO DE EMBALAGENS LTDA -EPP', 'BALNEARIO CAMBORIU', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (80446, 'SUPERMERCADO BAHAMAS LTDA', 'JUIZ DE FORA', 604);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (61999, 'BISTEK SUPERMERCADOS LTDA.', 'NOVA VENEZA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (286630, 'IMBITUBA ATLETICO CLUBE', 'IMBITUBA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (122343, 'DOCE FESTA RIBEIRAO PROD.ALIM.LTDA.', 'RIBEIRAO PRETO', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (258113, 'NESTOR LACHMAN E CIA LTDA.', 'PATO BRANCO', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (266698, 'MAKRO ATACADISTA S/A', 'SAO LEOPOLDO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (166090, 'MAKRO ATACADISTA S.A.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41114, 'MAKRO ATACADISTA S.A.', 'CAMPINAS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (248193, 'MAKRO ATACADISTA S.A.', 'OSASCO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (104256, 'MAKRO ATACADISTA S.A.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (208485, 'MAKRO ATACADISTA S.A.', 'JOINVILLE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (197718, 'MAKRO ATACADISTA S.A.', 'JUIZ DE FORA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (222810, 'FERREIRA PIANO COMERCIO DE EMBALAGENS LT', 'CURITIBA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (9237, 'COMAPLA CASA DOS DESCARTAVEIS LTDA', 'PORTO ALEGRE', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (273040, 'IRMAOS ANDREAZZA LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (244910, 'AGUIMAR ALVES FERREIRA ME.', 'ORLANDIA', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (117676, 'XANDOCA ARTIGOS PARA FESTAS LTDA.', 'FLORIANOPOLIS', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (139840, 'MAKRO ATACADISTA S.A.', 'SAO LUIS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (275930, 'MAKRO ATACADISTA S/A', 'CAMPOS GOYTACAZES', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (167088, 'NECTAR PRODUTOS ALIMENTARES LTDA', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (292478, 'J. CRISTOVAO', 'BLUMENAU', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (195006, 'ADREMIL COMERCIAL LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (33430, 'IMBRALIT IND.COM.ARTEF.FIBROC.LTDA', 'CRICIUMA', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (87106, 'VONPAR REFRESCOS S/A', 'ANTONIO CARLOS', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (61018, 'SERGUN YOUL ESHA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (224219, 'COMERCIO DOIS IRMAOS SR LTDA.', 'JOINVILLE', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (80373, 'REFRIGERANTES COROA LTDA.', 'DOMINGOS MARTINS', 1341);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (278025, 'JC SUPRIMENTOS LTDA - ME.', 'CRICIUMA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (56642, 'AMARETTI BEBIDAS LTDA.', 'ICARA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (286281, 'FELIX MARQUES NETO', 'SAO JOAO DEL REI', 604);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (65064, 'EMBLS.SABRINA LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (52337, 'M.M.ROSSO SUPERMERC.LTDA.', 'CRICIUMA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (177423, 'GRUPO PAULISTA DE DESCARTAVEIS LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (268127, 'UNIMED CRICIUMA COOP TRAB MED REG CARBON', 'CRICIUMA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (283312, 'CAMARF_S IND.E COM.DE SORVETES LTDA.ME.', 'MARINGA', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (259160, 'BATISTELLI E CIA LTDA.', 'CURITIBA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (288829, 'SUL FESTAS COM. DE ARTS DECORATIVOS LTDA', 'LAJEADO', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (277860, 'MOVEIS CORREA BACK LTDA', 'CRICIUMA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (292346, 'HOSSOKAWA COM.REP.PROD.HIGIENE LIMPEZA L', 'MANAUS', 566);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (273562, 'LWR DE CARVALHO LTDA', 'CALDAS NOVAS', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (287091, 'CENTRO DE COMPRAS ZALESKI LTDA', 'HORIZONTINA', 752);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (117269, 'FRATINI E CIA.LTDA.', 'JOACABA', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (196509, 'KING FRIOS COM.DIST.DE FRIOS LTDA.', 'APARECIDA DE GOIANIA', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (179922, 'LA PAOLLA IND.E COM.DE ALIM.LTDA.', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (257923, 'COMEPLAST PROD.EQUIP.P/EMBALAGENS LTDA.', 'BENTO GONCALVES', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (25470, 'J MOREIRA EMBALAGENS LTDA', 'CAMPO GRANDE', 1473);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (235040, 'N V TOLEDO E CIA LTDA.', 'APUCARANA', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (292400, 'DISTRIBUIDORA CAMPISTA LTDA - FILIAL -', 'JUIZ DE FORA', 604);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (91570, 'ACEFRAN-COMERCIO DE EMBALAGENS LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (178551, 'MAKRO ATACADISTA S.A.', 'NOVA IGUACU', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (50431, 'MAKRO ATACADISTA S.A.', 'VOTORANTIM', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (259098, 'MAKRO ATACADISTA S/A', 'PIRACICABA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (157414, 'MAKRO ATACADISTA S.A.', 'ANANINDEUA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41084, 'MAKRO ATACADISTA S.A.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41130, 'MAKRO ATACADISTA S.A.', 'RIO DE JANEIRO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (277576, 'MAKRO ATACADISTA S/A', 'VOLTA REDONDA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41157, 'MAKRO ATACADISTA S.A.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (84522, 'MAKRO ATACADISTA S.A.', 'GUARA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (48135, 'MAKRO ATACADISTA S.A.', 'PRAIA GRANDE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (283789, 'MAKRO ATACADISTA S/A', 'RIO BRANCO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (163481, 'INDUSTRIA DE SORVETES SARAMEL LTDA.', 'CURITIBA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (271748, 'RR COM.DE BEBIDAS LTDA.', 'MORRO REUTER', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (45136, 'CIA ZAFFARI COM.E IND.', 'PORTO ALEGRE', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (161500, 'COBRA IND. COM. DE EMBALAGENS LTDA', 'CARLOS BARBOSA', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (89818, 'REAL SUCOS LTDA.', 'FORTALEZA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (32158, 'B.A.INDUSTRIAL LTDA', 'PARA DE MINAS', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (141097, 'FETT FESTAS LTDA - ME', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (86924, 'TUDEM COM.EMBLS.DESC.LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (209066, 'VILACA COML.LTDA.', 'BELO HORIZONTE', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (292443, 'PULIRE RIO COMERCIAL LTDA-ME', 'DUQUE DE CAXIAS', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (268496, 'MAIS SABOR IND.E COM.DE REFRIG.LTDA', 'FORTALEZA', 1872);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (266388, 'MAKRO ATACADISTA S/A', 'PETROLINA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (209988, 'COMERCIAL IMP.EXP.METAPUNTO LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (76384, 'VONPAR REFRESCOS S.A.', 'BLUMENAU', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (264075, 'MARCUS VINICIUS STOLL', 'CANOAS', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (51233, 'JOAO ELPIDIO NICARETTA', 'XANXERE', 1864);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (182826, 'RUBI PRODUTOS DE LIMPEZA & HIGIENE LTDA', 'SAMAMBAIA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (158917, 'AMIFEST-ASSOC.DE AMIGOS DA OKTOBERFEST', 'IGREJINHA', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (280704, 'CROMOS S/A TINTAS GRAFICAS', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (23540, 'COFERPAN COM.FERM.PROD.PANIF.LTDA.', 'LONDRINA', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (292494, 'ACADEMIA DO ACAI LTDA ME', 'BALNEARIO CAMBORIU', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (2569, 'CADIMENSE  EMBALAGENS E DESC.LTDA - EPP', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (141828, 'COLUMBIA COML. PAULISTA LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (174106, 'INTEGRADA COOP. AGROINDUSTRIAL.', 'ASSAI', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (276952, 'AUTOSNACK RESTAURANTE DO TREVO LTDA', 'RIBEIRAO PRETO', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (155365, 'IZANINO BARCELOS JUNIOR ME', 'CRICIUMA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (37460, 'ANTONIO MANOEL', 'ICARA', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (109665, 'JML-PLASTIC COM.DE EMBLS.LTDA-ME', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (291706, 'BRINKMAISFESTA COMERCIO DE PRODUTOS LTDA', 'CASCAVEL', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (148300, 'EMBALEBEM COML.LTDA.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (244147, 'BEST FOOD COMERCIO DE ALIMENTOS LTDA.', 'IGARASSU', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (123005, 'CORDOBA COM.DE PRODUTOS DESC.LTDA.', 'CEILANDIA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (214710, 'DANIEL HENRIQUE DA SILVA BORGES E PIRES', 'JATAI', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (230286, 'GOLLDEN FOOD IND.COM.DE ALIM.LTDA.', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (252522, 'IWDJ-COM. DE CONFECCOES E EMBALAGENS LTD', 'SAO JOSE', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (268607, 'MARCIO DA SILVA RODRIGUES ME', 'GOIANIA', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (265187, 'DISTRI.DE EMBALAGENS CASTROPIL LTDA', 'GUARULHOS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (168130, 'REGINA CELIA FERNANDES ME', 'CURITIBA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (245054, 'VITAPEL PAPEIS E EMBALAGENS LTDA.', 'APUCARANA', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (178624, 'MOYSA & FERNANDES LTDA.', 'SAO JOSE DOS PINHAIS', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (84247, 'CLUBE RECREATIVO DORES', 'SANTA MARIA', 892);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (286095, 'CANASAN DO BRASIL COM. DE ALIM.LTDA EPP', 'SAO PAULO', 1414);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (77666, 'BEBIDAS CICHELERO LTDA', 'CARLOS BARBOSA', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (285595, 'SIARE COM.E REP.DE DESCARTAVEIS LTDA-ME.', 'RIBEIRAO PRETO', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (282820, 'REST PASTA DI ROMA LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (50393, 'MAKRO ATACADISTA S.A.', 'SAO JOSE DOS CAMPOS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41106, 'MAKRO ATACADISTA S.A.', 'PINHAIS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (126799, 'MAKRO ATACADISTA S.A.', 'CUIABA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (232378, 'MAKRO ATACADISTA S.A.', 'CAMPINAS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (131997, 'MAKRO ATACADISTA S.A.', 'CAMPO GRANDE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (230081, 'MAKRO ATACADISTA S.A.', 'SANTO ANDRE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (219908, 'MAKRO ATACADISTA S.A.', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (288799, 'MAKRO ATACADISTA S/A', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41726, 'DOROPEL COMERCIO DE PAPEIS LTDA.', 'DIADEMA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (281964, 'MAKRO ATACADISTA S/A', 'PALMAS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (273414, 'MAKRO ATACADISTA S/A', 'PRESIDENTE PRUDENTE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (185337, 'MAKRO ATACADISTA S.A.', 'TERESINA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (42200, 'COM.REPRES.BELLATO LTDA', 'LAGES', 1864);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (164062, 'ASPACK DIST.LTDA.', 'CONTAGEM', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (97969, 'SUPER SIAM DISTR.DE MASSAS E SALG.LTDA.', 'NITEROI', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (275786, 'MARTINS E AGOSTINHO SUCOS LTDA', 'PRESIDENTE PRUDENTE', 1414);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (205427, 'PEDRO ELIZEU JOSE DA SILVA ME.', 'FLORIANOPOLIS', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (126535, 'A NIPOPLAST EMB.E ART.PLAST.LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (49131, 'BRASLIMPO COMERCIAL LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (287288, 'LANCHONETE TENTACAO DO MATE LTDA', 'CAMBORIU', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (212725, 'JADER RUSSI DE SOUZA ME.', 'BALNEARIO CAMBORIU', 973);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (47554, 'TINGUI FACTORY ALIMENTOS LTDA.', 'COLOMBO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (292435, 'PADARIA DIVINA GULA LTDA', 'DIVINOLANDIA', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (19836, 'JUNCO IND.E COM.LTDA', 'UBERLANDIA', 337);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (283991, 'GILMARIO FERREIRA FELIPE-EPP', 'FORTALEZA', 1872);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (274810, 'UNASUL COMERCIO DE EMBALAGENS LTDA - ME', 'BRASILIA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (39322, 'ASSOCIACAO IMBRALIT', 'CRICIUMA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (257028, 'E D COM.DE PRODUTOS DE LIMPEZA LTDA.', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (243418, 'ROSA ANGELA PASCUALOTE', 'URUACU', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (107514, 'DISTRIBUIDORA ATACADISTA NETTO LTDA.', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (281689, 'LECOMAG ALIMENTOS LTDA-ME', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (255912, 'AMPABA ASSOC. MINE PEQ PROD RUR B.ALEGRE', 'BURITI ALEGRE', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (106640, 'CACOLA EMBELAGENS LTDA.', 'RIBEIRAO PRETO', 1333);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (283967, 'AGM COMERCIO VAREJISTA DE SUCOS LTDA EPP', 'SAO JOSE DOS CAMPOS', 1414);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (283010, 'J.E.M COMERCIAL E DISTRIBUIDORA LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (198404, 'JLM RESTAURANTE LTDA', 'BRASILIA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (167614, 'SONIA MARIA FERREIRA DOS SANTOS ME.', 'SUZANO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (230405, 'SORVETERIA CASTELO LTDA', 'FORMOSA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (290467, 'IRMAOS ANDREAZZA LTDA', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (276502, 'NATANAEL DOURADO - ME', 'OURINHOS', 1180);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (43443, 'RICCIPLAST IND.COM.DE PLASTICOS LTDA', 'PASSO FUNDO', 752);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (4839, 'A FRIA - PRODUTOS PARA SORVETERIA LTDA-E', 'CEILANDIA', 779);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (114049, 'AGUA MINERAL SANTA CATARINA LTDA.', 'PALHOCA', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (289078, 'CENTROCARDIO CEN.DE CARDIO.DE NIT.LTDA', 'NITEROI', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (190055, 'FARMOQUIMICA S/A', 'RIO DE JANEIRO', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (233234, 'RAFAEL A.S.LAMEGO DE ALMEIDA', 'SAO JOAO DE MERITI', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (248410, 'COMERCIAL DE CEREAIS ZAFFARI LTDA', 'PASSO FUNDO', 752);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (209074, 'GUILHERME E. BASSEGGIO ME.', 'CARLOS BARBOSA', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (56189, 'CAREN COMERCIO DE EMBALAGENS LTDA-EPP.', 'FEIRA DE SANTANA', 183);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (23752, 'SORVETERIA REGINA LTDA-ME', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (14443, 'IMPORTADORA E EXPORT.DE CEREAIS S.A.', 'LAJEADO', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (292133, 'TOTAL PACK COM.DIST. EMBALAGENS LTDA ME', 'SAO JOSE', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (190713, 'NEUMI MARQUES FEITOSA', 'PAULO AFONSO', 1651);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (286516, 'SUCOLANDIA SUCOS RIO PRETO LTDA', 'S JOSE DO RIO PRETO', 1414);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (123170, 'DISTRIBUIDORA DISSEL LTDA', 'RECIFE', 1058);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (213489, 'J.FERREIRA MARTINS LTDA.ME.', 'FLORIANOPOLIS', 1074);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (145017, 'MAKRO ATACADISTA S.A.', 'MACEIO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (123943, 'MAKRO ATACADISTA S.A.', 'NATAL', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41068, 'MAKRO ATACADISTA S.A.', 'CONTAGEM', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (41076, 'MAKRO ATACADISTA S.A.', 'RIO DE JANEIRO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (24198, 'MAKRO ATACADISTA S.A.', 'RECIFE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (125334, 'RIO BRANCO COM.E IND.DE PAPEIS LTDA', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (279285, 'MAKRO ATACADISTA S/A', 'TAUBATE', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (259144, 'WANDERLEY E EMBALAGENS LTDA ME.', 'JABOATAO GUARARAPES', 1058);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (91375, 'EMBLS.ITABIRA LTDA', 'ITABIRA', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (267635, 'CASA DE SUCOS DE FRANCA LTDA ME', 'FRANCA', 1414);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (283266, 'REALEZA EMBALAGENS LTDA', 'IBIRITE', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (250147, 'INDUSTRIA DE SORVETES URCA LTDA EPP', 'CAXIAS DO SUL', 515);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (157392, 'DISTRIBUIDORA DE ALIM E BEB TAVARES LTDA', 'CRICIUMA', 1465);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (148440, 'MAKRO ATACADISTA S.A.', 'FLORIANOPOLIS', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (285986, 'TE TE FESTAS LTDA - FILIAL -', 'JUIZ DE FORA', 604);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (241660, 'KALUNGA COM.IND.GRAFICA LTDA.', 'BARUERI', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (282073, 'MILLER FAST FOOD ALIMENTOS LTDA', 'JANDIRA', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (135593, 'ADRILUR COM. PROD. LIM. E DESC. LTDA EPP', 'SAO PAULO', 19);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (214752, 'IRM?OS KUMADA LTDA ME', 'CALDAS NOVAS', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (40576, 'CLAERRO SORVETES LTDA.', 'ARAGUARI', 124);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (128996, 'LOJAS AMERICANAS S.A.', 'RECIFE', 27);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (34126, 'VONPAR REFRESCOS S/A', 'JOINVILLE', 701);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (211117, 'SOL DE MINAS - COMERCIO DE FRIOS LTDA - ', 'CURITIBA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (190608, 'ELIETE FEIJAO RODRIGUES', 'FORTALEZA', 1872);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (268895, 'D CLINICA COMERCIAL LTDA.', 'CURITIBA', 1627);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (268720, 'CEMA CENTRAL MINEIRA ATACADISTA LTDA', 'RIBEIRAO DAS NEVES', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (287300, 'ANTONIO EVILASIO CARDOSO-ME', 'CRICIUMA', 353);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (19704, 'DISTR.NACIONAL DE PAPEL EMBALAGENS LTDA.', 'CONTAGEM', 1538);
Insert into clientes
   (cd_cliente, nm_cliente, nm_cidade, cd_representante)
 Values
   (20150, 'IND.DE DOCES CASEIROS CROCHEMORE LTDA.', 'PELOTAS', 1873);