Insert into representantes
   (cd_representante, nm_representante)
 Values
   (353, 'D I R E T O');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1465, 'ALEXANDRE PACHECO');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1627, 'DIAMANTE REPRESENTACOES COMERCIAIS LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (19, 'DISCAM COMERCIO E REPRES. LTDA.');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (698, 'MELK & SID REPRES. LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (124, 'CARAVELA DO SUL REPRES.LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (27, 'PLASCOP RIO REPRES.LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (973, 'REPRESENTACOES COM.FRPL LTDA ME');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1414, 'RAULMAR BENKO GUERRA - ME');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (515, 'MARANGON - COMERCIO E REPRESENT. LTDA.');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1538, 'SOWAL REPRESENTACOES LTDA.');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1651, 'LINOS REPRESENTACOES LTDA.');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1457, 'DOMINGOS REPRESENTACOES LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (604, 'REPRES. JOSE MARIA FIGUEIRAS & CIA. LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1074, 'RUY CARLOS LOSSE');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (752, 'JURANDIR TIBULO E CIA LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1180, 'A.T.MIYAZAKI & CIA LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (779, 'PAIVA REPRES.COML.LTDA/BRASILIA-DF');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (337, 'FLAVIO REPRESENTACOES LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1333, 'SIARE REPRESENTACOES LTDA.');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (183, 'MACIEL COM. DE DESCART. LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (892, 'MENOTI COMERCIO E REPRESENTACOES LTDA.ME');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1864, 'GOUTZER REPRESENTACOES COMERCIAIS LTDA-M');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (914, 'E T REPRESENTACOES COML. LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (701, 'BENE SUL COMERCIO E REPRESENTACAO LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1716, 'L S COELHO REPRESENTACOES LTDA ME');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (566, 'CHUMBINHO REPRESENTACOES LTDA.');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1341, 'C E G COM. E REPRESENTACOES LTDA.');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1473, 'GONCALVES & ALMEIDA LTDA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1872, 'DIRETO-FORTALEZA');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1058, 'LEMES REPRESENTACOES E COMERCIO LTDA.');
Insert into representantes
   (cd_representante, nm_representante)
 Values
   (1873, 'DIRETO PELOTAS');