Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (475851, 279862, '2010-09-01', 2, '2010-09-20', 
    'Salim via fone');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (908999, 244422, '2010-09-01', 3, '2010-09-04', 
    'avisar qdo tiver o material');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4879, 126608, '2010-09-01', 2, '2010-09-04', 
    'Faturar 01/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4880, 176877, '2010-09-01', 2, '2010-09-04', 
    'Faturar 01/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91003, 276952, '2010-09-01', 2, '2010-09-15', 
    'I.PED. REF. 25CXS DE DEVOLUCAO DA NF 76520');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (541422, 155365, '2010-09-01', 2, '2010-09-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (2895, 133825, '2010-09-01', 2, '2010-09-17', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (496530, 14010, '2010-09-01', 2, '2010-09-13', 
    'Junto pedido 496531-Bonificacao NF.eletronicanfe@superalvorada.com.br');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (290243, 280232, '2010-09-01', 2, '2010-10-20', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (2336, 147982, '2010-09-01', 2, '2010-09-20', 
    '.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (125121, 37460, '2010-09-01', 2, '2010-09-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (47048, 56243, '2010-09-01', 2, '2010-11-08', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615464, 63517, '2010-09-01', 2, '2010-09-16', 
    'VENCIMENTO COMBINADO 23/12-ENTREGA COMBINADA 09/09 AGENDAR E PALETIZAR');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615468, 282898, '2010-09-01', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615469, 167614, '2010-09-01', 2, '2010-09-29', 
    'I - MANDAR 15 DIAS APOS O PED.615192 - fat. 30/09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615457, 63517, '2010-09-01', 2, '2010-09-17', 
    'VENCIMENTO COMBINADO 24/12-ENTREGA COMBINADA 10/09 TEM QUE AGENDAR E PALETIZAR');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615458, 63517, '2010-09-01', 2, '2010-09-17', 
    'VENCIMENTO COMBINADO 24/12-ENTREGA COMBINADA 10/09 TEM QUE AGENDAR E PALETIZAR');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615459, 63517, '2010-09-01', 2, '2010-09-09', 
    'VENCIMENTO COMBINADO 23/12 TEM QUE AGENDAR E PALETIZAR');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615460, 63517, '2010-09-01', 2, '2010-09-15', 
    'VENCIMENTO COMBINADO 22/12 AGENDAR E PALETIZAR');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615461, 63517, '2010-09-01', 2, '2010-09-30', 
    'VENCIMENTO COMBINADO 22/12-ENTREGA COMBINADA 08/09 AGENDAS E PALETIZA');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480505, 160881, '2010-09-01', 2, '2010-09-20', 
    'Optante do Simples');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480506, 159387, '2010-09-01', 2, '2010-09-20', 
    'Optante do Simples');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480507, 277428, '2010-09-01', 2, '2010-09-13', 
    'Optante do Simples');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480508, 288098, '2010-09-01', 2, '2010-09-13', 
    'Optante do Simples');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615480, 179183, '2010-09-01', 3, '2010-09-15', 
    'PEDIDO 0238154528441 - VENC.FIXO 15/09/2010-Cancelado pedidos errados sistema Makro');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480509, 195863, '2010-09-01', 2, '2010-09-04', 
    'Optante do Simples');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615465, 109665, '2010-09-01', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615454, 177423, '2010-09-01', 2, '2010-11-10', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (286666, 250791, '2010-09-01', 2, '2010-09-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14601, 25933, '2010-09-01', 2, '2010-10-22', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784238, 230405, '2010-09-01', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (114601, 25933, '2010-09-01', 2, '2010-10-29', 
    '.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (268222, 268127, '2010-09-01', 2, '2010-09-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14881, 290467, '2010-09-01', 2, '2010-09-20', 
    'Faturar 01/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814475, 27880, '2010-09-01', 2, '2010-09-06', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14602, 250813, '2010-09-01', 2, '2010-11-19', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14603, 283312, '2010-09-01', 2, '2010-09-17', 
    'I. Favor verificar a qualidade da impressao pois noultimo pedido foi aberta reclamacao.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (587411, 289582, '2010-09-01', 2, '2010-09-04', 
    'Everton via fone');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14604, 276502, '2010-09-01', 2, '2010-10-22', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909025, 259160, '2010-09-01', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131785, 274186, '2010-09-01', 2, '2010-09-13', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615479, 116815, '2010-09-01', 3, '2010-09-14', 
    'PEDIDO 0238154528420 - VENC.FIXO 14/09/2010-Cancelado pedidos errados sistema Makro');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (751098, 43443, '2010-09-01', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (24604, 259950, '2010-09-01', 2, '2010-10-22', 
    'I.CLIENTE REMESSA 259969 JONAS LEITE');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (47052, 249076, '2010-09-02', 3, '2010-10-04', 
    'I.PED.CANCELADO CLIENTE COMPROU DA DIXIE (SEM TEMPO P ESPERAR)');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91004, 281662, '2010-09-02', 2, '2010-09-15', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (460109, 227870, '2010-09-02', 2, '2010-10-27', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14882, 288829, '2010-09-02', 2, '2010-09-13', 
    'Faturar 02/09/2010 - PRAZO AUTORIZADO POR IVAN');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (590, 233277, '2010-09-02', 2, '2010-11-01', 
    'I - FATURAR 20/10 - 40CXS - Digitado o pedido 59315 com as 61 cxs da Tampa.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (90209, 229105, '2010-09-02', 2, '2010-09-22', 
    'Junto pedido 90210-bonificagco cod.8943-5 15cxs');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4883, 100293, '2010-09-02', 2, '2010-09-27', 
    'Faturar 02/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (908930, 291706, '2010-09-02', 3, '2010-09-13', 
    'Aguardar reajuste devido a arte nova');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (908931, 233170, '2010-09-02', 2, '2010-11-08', 
    'I. Urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909994, 268127, '2010-09-02', 3, '2010-09-05', 
    'selecionar o pedido para fazer a troca da nota77860 que foi faltando 2 cxs tampa');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615483, 148300, '2010-09-02', 2, '2010-09-16', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615484, 251976, '2010-09-02', 2, '2010-09-09', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615485, 244147, '2010-09-02', 2, '2010-09-27', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (558863, 123005, '2010-09-02', 2, '2010-10-10', 
    'I.CP550 RHELKS PEDIDO PROGRAMADO P/ 10/10/2010.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (988552, 123005, '2010-09-02', 2, '2010-10-25', 
    'I. PP300 RHELKS');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (566333, 123005, '2010-09-02', 2, '2010-11-22', 
    'FATURA 10/11 ENTREGAR 15/11/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909995, 277860, '2010-09-02', 2, '2010-10-25', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (963284, 272558, '2010-09-02', 3, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (932584, 272558, '2010-09-02', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (1814, 46744, '2010-09-02', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14885, 63665, '2010-09-02', 2, '2010-09-20', 
    'Faturar 02/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (496531, 14010, '2010-09-02', 2, '2010-09-06', 
    'Junto pedido 496530-Ref.verba aniversario');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (3357, 280585, '2010-09-02', 2, '2010-09-10', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91005, 117552, '2010-09-02', 2, '2010-09-17', 
    'Inclusao do Saldo do Pedido 91005 de T.C. - 5 cxsdo PR150.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (23543, 37460, '2010-09-02', 2, '2010-09-05', 
    'Pedido via fone Marciel.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (815181, 239356, '2010-09-02', 2, '2010-09-15', 
    'PED.BONIF.REF.5% DO VALOR DOS PEDIDOS MES AGOSTO -ACORDO COML.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (57886, 57886, '2010-09-02', 2, '2010-10-04', 
    'Pedido via e-mail Sinesio');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784239, 4839, '2010-09-02', 2, '2010-09-27', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (599, 114049, '2010-09-02', 2, '2010-10-04', 
    'I - DEPOS.50% EFETUADO 6/09 - OUTRO 50%DEPOSITADOEM 27/09/2010.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (292346, 292346, '2010-09-02', 3, '2010-09-27', 
    'Pedido via e-mail');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (13358, 214710, '2010-09-02', 2, '2010-09-17', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909027, 200433, '2010-09-02', 2, '2010-10-04', 
    'urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615498, 192724, '2010-09-02', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615493, 266230, '2010-09-02', 2, '2010-09-08', 
    'URGENTE');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615495, 267708, '2010-09-02', 2, '2010-10-22', 
    'I - ENTREGAR DIA 22/10/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615489, 120561, '2010-09-02', 2, '2010-09-09', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615496, 267708, '2010-09-02', 3, '2010-11-23', 
    'I. CANCELADO P/ SOLICICATAO ROSA');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615497, 267708, '2010-09-02', 3, '2010-12-17', 
    'PEDIDO CANCELADO P/ ROSA-DISCAM');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (124545, 268119, '2010-09-02', 2, '2010-09-13', 
    'Pedido via e-mail');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615481, 228540, '2010-09-02', 2, '2010-09-23', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615482, 73210, '2010-09-02', 2, '2010-09-09', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615490, 179876, '2010-09-02', 2, '2010-09-09', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615494, 177423, '2010-09-02', 2, '2010-10-25', 
    'I.ULTIMO PED. COM 90DD -');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (1900, 280267, '2010-09-02', 2, '2010-11-22', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (1815, 280267, '2010-09-02', 2, '2010-10-15', 
    'FELIPE PODE FATURAR URGENTE');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (1816, 161802, '2010-09-02', 2, '2010-10-18', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784240, 282880, '2010-09-02', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784241, 32611, '2010-09-02', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615502, 63517, '2010-09-02', 2, '2010-09-10', 
    'VENCIMENTO COMBINADO  24/12 ENTREGA COMBINADA 10/09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615503, 63517, '2010-09-02', 2, '2010-10-01', 
    'VENCIMENTO COMBINADO 24/12-ENTREGA COMBINADA 10/09 TEM QUE AGENDAR E PALETIZAR');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73470, 243906, '2010-09-02', 2, '2010-09-05', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73471, 279420, '2010-09-02', 2, '2010-09-05', 
    'OPTANTE PELO SIMPLES NACIONAL - S.T. = 3,48%');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909996, 243728, '2010-09-02', 2, '2010-09-06', 
    'urgentissimo');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909997, 243728, '2010-09-02', 1, '2011-02-28', 
    'PEDIDO CANCELADO - ATRASO NA PRODUCAO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (13359, 273562, '2010-09-02', 2, '2010-09-17', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14884, 230286, '2010-09-02', 2, '2010-09-20', 
    'Faturar 02/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (123364, 123005, '2010-09-02', 2, '2010-10-29', 
    'I - CP330 RHELKS PEDIDO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480510, 252522, '2010-09-02', 2, '2010-09-05', 
    'Verificar Razao social');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615492, 177423, '2010-09-02', 2, '2010-09-27', 
    'I - ULTIMO PEDIDO C/ 90DD -');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814476, 289078, '2010-09-02', 2, '2010-10-18', 
    'I - DEPOSITO EFETUADO DIA 06/09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909026, 200565, '2010-09-02', 2, '2010-09-05', 
    'URGENTE');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (13357, 268607, '2010-09-02', 2, '2010-09-10', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814479, 190055, '2010-09-02', 2, '2010-09-14', 
    'FATURAR DIA 14/09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615491, 265187, '2010-09-02', 2, '2010-10-07', 
    'Rosa via email solicitou cancelar o saldo.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (52263, 19348, '2010-09-02', 2, '2010-10-25', 
    'I - ENVIAR FAX DA NF PARA CRISTINI - IMBRALIT. AVISEI PRAZO DE ENTREGA 50DIAS.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814478, 233234, '2010-09-02', 2, '2010-10-25', 
    'CLIENTE REMESSA 269565 RICARDO CARLOS RODRIGUES');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (10940, 248410, '2010-09-03', 2, '2010-10-04', 
    'Saldo da ordem de compra 273350.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14886, 209074, '2010-09-03', 2, '2010-09-13', 
    'Faturar 03/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (10942, 82970, '2010-09-03', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (3097, 56189, '2010-09-03', 2, '2010-09-29', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (10945, 287091, '2010-09-03', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14887, 23752, '2010-09-03', 2, '2010-12-10', 
    'I - Produzir e faturar em 15/10/2010.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (2337, 115843, '2010-09-03', 3, '2010-09-07', 
    'faturar apos representante autorizar');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (2527, 255696, '2010-09-03', 2, '2010-10-18', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909028, 117269, '2010-09-03', 3, '2010-09-28', 
    '.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909029, 168130, '2010-09-03', 2, '2010-09-27', 
    'Marina via email solicitou cancelar o saldo do pedido.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (90210, 229105, '2010-09-03', 2, '2010-09-27', 
    'Junto Ped.90209-Bonif.3% pedido 90209-Acordo coml');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (33359, 196509, '2010-09-03', 2, '2010-10-18', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4888, 14443, '2010-09-03', 2, '2010-11-02', 
    'Marangon via e-mail solicitou cancelar o saldo do pedido.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14889, 179922, '2010-09-03', 2, '2010-09-13', 
    'Faturar 03/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4890, 179922, '2010-09-03', 2, '2010-11-02', 
    'I - Produzir e faturar ate 15/10/2010. -');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (287383, 990990, '2010-09-03', 2, '2010-09-06', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (1817, 218499, '2010-09-03', 2, '2010-10-26', 
    'I - REAJUSTADO 5% E REAJUSTAR MAIS 5% NO PROXIMO PEDIDO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814480, 264555, '2010-09-03', 2, '2010-09-13', 
    'FATURAR URGENTE!');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14606, 245054, '2010-09-03', 2, '2010-09-17', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (114606, 245054, '2010-09-03', 2, '2010-10-27', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (908935, 178624, '2010-09-03', 2, '2010-09-20', 
    'urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4891, 77119, '2010-09-03', 2, '2010-09-06', 
    'Faturar 03/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91009, 269999, '2010-09-03', 2, '2010-09-17', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4892, 257923, '2010-09-03', 2, '2010-09-13', 
    'Faturar 03/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814483, 273015, '2010-09-03', 2, '2010-09-13', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909031, 289515, '2010-09-03', 2, '2010-09-13', 
    'URGENTE');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (551211, 25470, '2010-09-03', 2, '2010-10-04', 
    'Pedido Iosmar via e-mail');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (46221, 84247, '2010-09-03', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (2338, 147982, '2010-09-03', 2, '2010-09-20', 
    'Alterar p/CONSUMO quando for faturar - pedido p/atender o refeitorio da Vonpar.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73472, 125768, '2010-09-03', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480512, 232653, '2010-09-03', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (12339, 5002, '2010-09-03', 2, '2010-09-20', 
    'faturar e entregar urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73473, 109428, '2010-09-03', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814482, 182974, '2010-09-03', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (10981, 80446, '2010-09-03', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131786, 286095, '2010-09-03', 2, '2010-09-28', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131787, 290386, '2010-09-03', 2, '2010-10-01', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615517, 148636, '2010-09-03', 2, '2010-10-08', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909998, 61999, '2010-09-03', 2, '2010-10-26', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910000, 286630, '2010-09-03', 2, '2010-09-21', 
    'urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (908936, 221716, '2010-09-03', 2, '2010-09-20', 
    'Imediato');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814481, 288756, '2010-09-03', 2, '2010-09-06', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14605, 235040, '2010-09-03', 2, '2010-09-17', 
    'memso cliente que 245054');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909030, 244430, '2010-09-03', 2, '2010-09-20', 
    'cliente vai analisar o material depois comprara p/fechar 1.000 cx');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480511, 292133, '2010-09-03', 2, '2010-10-07', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73474, 140678, '2010-09-04', 2, '2010-09-14', 
    'OPTANTE PELO SIMPLES NACIONAL - S.T. = 3,48%');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73475, 279420, '2010-09-04', 2, '2010-09-29', 
    'I - FATURAMENTO: 23/09/10 - ENTREGA: 24/09/10 (EVENTO - OPTANTE PELO SIMPLES NACIONAL - S.T. = 3,48%');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73476, 279420, '2010-09-04', 2, '2010-10-12', 
    'I - 100 CXS. - FAT.: 05/10/10 -100 CXS. - FAT.: 11/10 - OPTANTE PELO SIMPLES NACIONAL - S.T. = 3,48%');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73477, 279420, '2010-09-04', 2, '2010-11-17', 
    'FAT.10/11/10-CLIENTE REMESSA RETIRADO PELO FLAVIOCONFORME CONVERSADO COM CLIENTE');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73479, 86495, '2010-09-04', 2, '2010-09-28', 
    'OPTANTE PELO SIMPLES NACIONAL - S.T. = 3,48%');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (10949, 284327, '2010-09-04', 2, '2010-10-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73478, 279420, '2010-09-04', 2, '2010-12-10', 
    'FAT. 10/12 - CLIENTE REMESSA RETIRADO PELO FLAVIO.CONFORME CONVERSADO COM CLIENTE');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (3852, 190713, '2010-09-06', 2, '2010-09-27', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4893, 85367, '2010-09-06', 2, '2010-09-16', 
    'Faturar 06/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (22337, 292400, '2010-09-06', 2, '2010-09-16', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131788, 289493, '2010-09-06', 2, '2010-10-01', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14895, 77666, '2010-09-06', 2, '2010-09-09', 
    'Faturar 06/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14894, 91570, '2010-09-06', 2, '2010-09-30', 
    'Faturar 06/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (255562, 990990, '2010-09-06', 2, '2010-09-09', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131789, 286516, '2010-09-06', 2, '2010-10-01', 
    'I.SAIR JUNTO C/ 131791');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (669887, 123170, '2010-09-06', 2, '2011-01-17', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131792, 261580, '2010-09-06', 2, '2010-10-29', 
    'I.autorizado pelo Raulmar incluir 1cx Papa Tuttysestava perdida no estoque');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91010, 285595, '2010-09-06', 2, '2010-10-01', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131791, 286516, '2010-09-06', 2, '2010-10-01', 
    'SAIR JUNTO C/ 131789(BONIFICACAO REF. ACORDO COML.1%)');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14896, 282820, '2010-09-06', 2, '2010-09-16', 
    'Faturar 06/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4897, 123080, '2010-09-06', 2, '2010-09-30', 
    'Faturar em 30/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91011, 122343, '2010-09-06', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480514, 213489, '2010-09-06', 2, '2010-09-16', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909032, 258113, '2010-09-06', 2, '2010-09-23', 
    'Marina via email solicitou cancelar o saldo do pedido.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14608, 173070, '2010-09-06', 2, '2010-10-08', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615632, 273147, '2010-09-06', 2, '2010-09-29', 
    'No Pedido Dele  :0249155028465 Vencimento Fixo :29/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615630, 178551, '2010-09-06', 2, '2010-09-22', 
    'No Pedido Dele  :0249155028439 Vencimento Fixo :22/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615634, 179353, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028440 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615635, 50440, '2010-09-06', 2, '2010-09-22', 
    'No Pedido Dele  :0249155028418 Vencimento Fixo :22/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615638, 271411, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028466 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615621, 266698, '2010-09-06', 2, '2010-09-27', 
    'No Pedido Dele  :0249155028462 Vencimento Fixo :27/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615622, 50423, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028416 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615624, 166090, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028437 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615626, 271403, '2010-09-06', 2, '2010-09-28', 
    'No Pedido Dele  :0249155028464 Vencimento Fixo :28/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615628, 50431, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028417 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615616, 50415, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028415 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615617, 167797, '2010-09-06', 2, '2010-10-07', 
    'No Pedido Dele  :0249155028436 Vencimento Fixo :07/10/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615605, 50393, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028411 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615609, 259098, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028460 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615610, 157414, '2010-09-06', 2, '2010-09-29', 
    'No Pedido Dele  :0249155028435 Vencimento Fixo :29/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615611, 50407, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028412 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615596, 250627, '2010-09-06', 2, '2010-10-07', 
    'No Pedido Dele  :0249155028455 Vencimento Fixo :07/10/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615598, 145017, '2010-09-06', 2, '2010-09-28', 
    'No Pedido Dele  :0249155028433 Vencimento Fixo :28/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615599, 41122, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028410 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615594, 41114, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028409 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615588, 41106, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028408 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615590, 248193, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028454 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615576, 233196, '2010-09-06', 2, '2010-09-22', 
    'No Pedido Dele  :0249155028452 Vencimento Fixo :22/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615578, 126799, '2010-09-06', 2, '2010-09-27', 
    'No Pedido Dele  :0249155028430 Vencimento Fixo :27/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615581, 41092, '2010-09-06', 2, '2010-09-27', 
    'No Pedido Dele  :0249155028407 Vencimento Fixo :27/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615583, 232378, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028453 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615584, 131997, '2010-09-06', 2, '2010-09-27', 
    'No Pedido Dele  :0249155028431 Vencimento Fixo :27/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615567, 54780, '2010-09-06', 2, '2010-09-28', 
    'No Pedido Dele  :0249155028428 Vencimento Fixo :28/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615568, 230081, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028451 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615573, 123943, '2010-09-06', 2, '2010-09-29', 
    'No Pedido Dele  :0249155028429 Vencimento Fixo :29/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615574, 41084, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028406 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615559, 41068, '2010-09-06', 2, '2010-09-24', 
    'No Pedido Dele  :0249155028404 Vencimento Fixo :24/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615560, 283630, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028482 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615561, 104256, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028427 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615562, 219908, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028449 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615566, 41076, '2010-09-06', 2, '2010-09-22', 
    'No Pedido Dele  :0249155028405 Vencimento Fixo :22/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615549, 288799, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028474 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615553, 18058, '2010-09-06', 2, '2010-09-30', 
    'No Pedido Dele  :0249155028426 Vencimento Fixo :300910');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615554, 41130, '2010-09-06', 2, '2010-09-22', 
    'No Pedido Dele  :0249155028403 Vencimento Fixo :22/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615555, 208485, '2010-09-06', 2, '2010-09-27', 
    'No Pedido Dele  :0249155028448 Vencimento Fixo :27/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615556, 280321, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028479 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615541, 202886, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028446 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615542, 277576, '2010-09-06', 2, '2010-09-22', 
    'No Pedido Dele  :0249155028473 Vencimento Fixo :22/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615546, 24198, '2010-09-06', 2, '2010-09-28', 
    'No Pedido Dele  :0249155028425 Vencimento Fixo :28/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615547, 210870, '2010-09-06', 2, '2010-09-24', 
    'No Pedido Dele  :0249155028447 Vencimento Fixo :24/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615548, 41149, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028402 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615540, 41157, '2010-09-06', 2, '2010-09-21', 
    'No Pedido Dele  :0249155028401 Vencimento Fixo :21/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615539, 84522, '2010-09-06', 2, '2010-09-27', 
    'No Pedido Dele  :0249155028424 Vencimento Fixo :27/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615521, 41726, '2010-09-06', 2, '2010-09-13', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615524, 194786, '2010-09-06', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615525, 125334, '2010-09-06', 2, '2010-09-13', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615658, 197718, '2010-09-06', 2, '2010-09-24', 
    'No Pedido Dele  :0249155028445 Vencimento Fixo :24/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615661, 279285, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028471 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615657, 52329, '2010-09-06', 2, '2010-09-28', 
    'No Pedido Dele  :0249155028423 Vencimento Fixo :28/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615650, 281964, '2010-09-06', 2, '2010-09-28', 
    'No Pedido Dele  :0249155028468 Vencimento Fixo :28/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615652, 190659, '2010-09-06', 2, '2010-09-28', 
    'No Pedido Dele  :0249155028443 Vencimento Fixo :28/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615653, 48135, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028422 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615656, 283789, '2010-09-06', 2, '2010-10-04', 
    'No Pedido Dele  :0249155028470 Vencimento Fixo :04/10/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615640, 179183, '2010-09-06', 2, '2010-09-27', 
    'No Pedido Dele  :0249155028441 Vencimento Fixo :27/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615642, 116815, '2010-09-06', 2, '2010-09-27', 
    'No Pedido Dele  :0249155028420 Vencimento Fixo :27/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615644, 273414, '2010-09-06', 2, '2010-09-23', 
    'No Pedido Dele  :0249155028467 Vencimento Fixo :23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615646, 50377, '2010-09-06', 2, '2010-09-27', 
    'No Pedido Dele  :0249155028421 Vencimento Fixo :27/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615647, 185337, '2010-09-06', 2, '2010-09-29', 
    'No Pedido Dele  :0249155028442 Vencimento Fixo :29/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (22338, 202967, '2010-09-06', 2, '2010-09-16', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909035, 163481, '2010-09-06', 2, '2010-10-01', 
    'I - MARINA AUTORIZOU FATURAR SEM IPI');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (35214, 259144, '2010-09-06', 2, '2011-01-17', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (13360, 44296, '2010-09-06', 2, '2010-09-29', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909034, 222810, '2010-09-06', 2, '2010-10-29', 
    'I - mesma arte do item 1895/3 - urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (3361, 65501, '2010-09-08', 2, '2010-10-07', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (33360, 261939, '2010-09-08', 2, '2010-09-23', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (13361, 247120, '2010-09-08', 2, '2010-09-16', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (2339, 9237, '2010-09-08', 2, '2010-10-04', 
    'faturar e entregar urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (22339, 271748, '2010-09-08', 2, '2010-09-22', 
    'faturar e entregar urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (23401, 45136, '2010-09-08', 2, '2010-09-20', 
    'faturar e entregar urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4802, 273040, '2010-09-08', 2, '2010-09-11', 
    'Faturar 08/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4801, 278580, '2010-09-08', 2, '2010-09-11', 
    'Faturar 08/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4900, 278580, '2010-09-08', 2, '2010-09-20', 
    'Faturar 08/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14899, 278599, '2010-09-08', 2, '2010-09-20', 
    'Faturar 08/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (596531, 42200, '2010-09-08', 2, '2010-09-27', 
    'Favor embarcar c/ urgencia,principalmente tampas epotes.Cliente solicitou via fone mandar PP120 s/TP');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14898, 161500, '2010-09-08', 2, '2010-09-20', 
    'Faturar 08/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (46570, 282120, '2010-09-08', 2, '2010-10-14', 
    'I - FATURAR DIA 07/10');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91014, 285595, '2010-09-08', 2, '2010-12-06', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (553464, 128554, '2010-09-08', 2, '2010-10-18', 
    'I - MANDAR AS TAMPAS URGENTES');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (544999, 51063, '2010-09-08', 2, '2010-10-03', 
    'I. urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (554544, 164062, '2010-09-08', 2, '2010-09-20', 
    'urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (655549, 252573, '2010-09-08', 2, '2010-09-11', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (985474, 89818, '2010-09-08', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814484, 97969, '2010-09-08', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (989875, 91375, '2010-09-08', 2, '2010-09-27', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (46571, 282120, '2010-09-08', 3, '2010-10-03', 
    'PEDIDO CANCELADO PELO REPRESENTANTE');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131793, 275786, '2010-09-08', 2, '2010-10-03', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (666554, 32158, '2010-09-08', 2, '2011-03-07', 
    'CARTA ISENCAO IPI VENCIDA-PRECO AUTORIZADO EVANDRO.DEPOSITO EFETUADO 27/12 R$ 27.005');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (666555, 32158, '2010-09-08', 2, '2011-03-14', 
    'PRECO AUTORIZADO EVANDRO- FAT. 14/03');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (666553, 32158, '2010-09-08', 2, '2011-04-15', 
    'PRECO AUTORIZADO EVANDRO-10CXS DE TAMPA A MENOS DEVIDO A TER IDO MAIS NO ULTIMO PEDIDO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (666552, 32158, '2010-09-08', 2, '2011-05-15', 
    'PRECO AUTORIZADO EVANDRO-FAT. 15/05');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615526, 141097, '2010-09-08', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615527, 86924, '2010-09-08', 2, '2010-09-15', 
    'Marcos via email solicitou cancelar o CP300 p/ atender o pedido total.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (99001, 244910, '2010-09-08', 2, '2010-10-03', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131794, 267635, '2010-09-08', 2, '2010-10-03', 
    'I. SAIR JUNTO C/ 131795 (BONIF.)');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131795, 267635, '2010-09-08', 2, '2010-10-03', 
    'I. SAIR JUNTO C/ 131794 - PED. BONF. REF. ACORDO COML. 1%');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (675755, 142484, '2010-09-08', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (665458, 209066, '2010-09-08', 2, '2010-09-11', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (766653, 283266, '2010-09-08', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (776642, 236446, '2010-09-08', 2, '2010-09-11', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480516, 117676, '2010-09-08', 2, '2010-09-27', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4803, 272264, '2010-09-08', 2, '2010-09-27', 
    'Faturar 08/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814485, 292443, '2010-09-08', 2, '2010-10-04', 
    'Nelma via email passou as tampas e os potes para TC.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (559597, 268496, '2010-09-08', 2, '2010-10-18', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480517, 205427, '2010-09-08', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4805, 191957, '2010-09-08', 2, '2010-11-08', 
    'I.Produzir e faturar em 25/10/2010.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4804, 250147, '2010-09-08', 2, '2011-01-17', 
    'I - Produzir e faturar em 18/10/2010.PASSEI P/104CXS REF.TAMPAS ENTREGUES COM PESO DE 2G.DEVOLUCAO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910001, 157392, '2010-09-08', 2, '2010-09-11', 
    'tentar mandar para dia 10/09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814486, 117960, '2010-09-08', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615565, 266388, '2010-09-08', 2, '2010-09-28', 
    'pedido 0249155028461 - venc.fixo 28/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615512, 126535, '2010-09-08', 2, '2010-09-22', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615515, 8303, '2010-09-08', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615689, 139840, '2010-09-08', 2, '2010-09-29', 
    'pedido 0249155028432 - venc.fixo 29/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615690, 275930, '2010-09-08', 2, '2010-09-23', 
    'pedido 0249155028458 - ven.fixo 23/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615691, 148440, '2010-09-08', 2, '2010-09-27', 
    'pedido 0249155028434 - venc.fixo 27/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814491, 273791, '2010-09-08', 2, '2010-11-30', 
    'FAT. 30/11');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814492, 273791, '2010-09-08', 2, '2010-12-31', 
    'I - FAT.30/12');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814487, 167088, '2010-09-08', 2, '2010-11-01', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814488, 167088, '2010-09-08', 2, '2010-11-30', 
    'I. FATURAR 30/11');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814489, 167088, '2010-09-08', 2, '2010-12-30', 
    'I - FATURAR 30/12');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (22559, 285986, '2010-09-08', 2, '2010-09-11', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (13363, 283193, '2010-09-08', 2, '2010-09-30', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (1819, 118630, '2010-09-08', 2, '2010-09-27', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615694, 70530, '2010-09-08', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615686, 279773, '2010-09-08', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615687, 279773, '2010-09-08', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615671, 209988, '2010-09-08', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615669, 106534, '2010-09-08', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615673, 241660, '2010-09-08', 2, '2010-09-15', 
    'ENTREGAR DA 14/09 TEM QUE PALETIZAR E AGENDAR ENVIAR ETIQUETAS PARA EN');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615674, 49131, '2010-09-08', 2, '2010-09-14', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615676, 63517, '2010-09-08', 2, '2010-09-15', 
    'VENCIMENTO COMBINADO 12/12-ENTREGA COMBINADA 13/09 TEM QUE PALETIZAR E AGENDAR.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615684, 247545, '2010-09-08', 2, '2010-11-01', 
    'I.ENTREGAR DIA 29/09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615672, 282073, '2010-09-08', 2, '2010-10-03', 
    'IMPRESSO PIZZA HUT ENTREGRA DIA 10/ 09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615697, 135593, '2010-09-08', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14609, 208434, '2010-09-08', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73480, 287288, '2010-09-08', 2, '2010-09-11', 
    'OPTANTE PELO SIMPLES NACIONAL - S.T. = 3,48%');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910003, 99244, '2010-09-08', 2, '2010-11-22', 
    'I-');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910004, 243728, '2010-09-08', 3, '2011-02-25', 
    'PEDIDO CANCELADO - ATRASO DE PRODUCAO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73481, 292478, '2010-09-08', 2, '2010-10-11', 
    'Deposito Ok - Elizandra');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910005, 243728, '2010-09-08', 3, '2010-11-30', 
    'entrega programada para 16/11.CANCELADO - FABRICA3 SEM CAPACIDADE DE ENTREGA');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910006, 243728, '2010-09-08', 3, '2010-12-01', 
    'entrega programada para 01/12 CANCELADO - FABRICA3 SEM CAPACIDADE DE ENTREGA');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910007, 243728, '2010-09-08', 3, '2010-12-16', 
    'entrega programada para 16/12. CANCELADO - FABRICA SEM CAPACIDADE DE ENTREGA');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73482, 212725, '2010-09-08', 2, '2010-10-18', 
    'REMESSA 271829-ROSA RUSSI - FAZER CARTA CORRECAOOPTANTE PELO SIMPLES NACIONAL - ST. = 3,48%');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (911019, 272752, '2010-09-08', 2, '2010-10-03', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73483, 241849, '2010-09-08', 2, '2010-10-18', 
    'CLIENTE REMESSA 271829 ROSA RUSSI DE SOUZA.OPTANTE PELO SIMPLES NACIONAL');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73484, 257737, '2010-09-08', 2, '2010-11-10', 
    'FAT.10/11-');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73485, 287288, '2010-09-08', 2, '2010-12-15', 
    'I - FAT.10/11-OPTANTE SIMPLES NACIONAL-S.T.=3,48%');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814493, 15946, '2010-09-08', 2, '2010-10-03', 
    'I - FATURAR DIA 22/09 E ENTREGAR DIA 30/09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615704, 47554, '2010-09-08', 2, '2010-10-04', 
    'I- ENTREGAR DIA 20/09/10');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615682, 227684, '2010-09-08', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (3853, 127116, '2010-09-08', 2, '2010-09-14', 
    'prazo acertado entre eliz e olivia');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73486, 212725, '2010-09-08', 2, '2011-01-07', 
    'I - FAT.10/12');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91068, 292435, '2010-09-08', 2, '2010-11-01', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814490, 273791, '2010-09-08', 2, '2010-11-01', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784244, 184721, '2010-09-08', 2, '2010-09-27', 
    'JAILSON CORTESIA');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615681, 195006, '2010-09-08', 2, '2010-09-29', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91015, 285595, '2010-09-08', 2, '2010-11-01', 
    'I.ALTEROU PARA 100CXS EM 04/10. FATURAR50CXS E 1SEAMANA DEPOIS AS OUTRAS 50CXS');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910008, 243728, '2010-09-08', 3, '2010-12-20', 
    'entrega programada para 01/01 CANCELADO - FABRICA3 SEM CAPACIDADE DE ENTREGA');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91019, 285595, '2010-09-09', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (13362, 214752, '2010-09-09', 2, '2010-10-04', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (33262, 40576, '2010-09-09', 2, '2010-10-04', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814494, 128996, '2010-09-09', 2, '2010-10-04', 
    'I.FATURAR DIA 22/09 E ENTREGAR DIA 30/09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4807, 271110, '2010-09-09', 2, '2010-09-12', 
    'Faturar 09/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (46126, 64220, '2010-09-09', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (3099, 281611, '2010-09-09', 3, '2010-11-01', 
    'ANTONIA SOLICITAOU O CANCELAMENTO DESTE PEDIDO 28-10-2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814495, 282634, '2010-09-09', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814496, 15482, '2010-09-09', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (452122, 250791, '2010-09-09', 2, '2010-09-13', 
    'Stelamaris/Almoxarifado Urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (2533, 19836, '2010-09-09', 2, '2010-11-01', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (561425, 286311, '2010-09-09', 2, '2010-09-13', 
    'Julio-TI retira na Expedicao');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (58120, 33430, '2010-09-09', 2, '2010-09-13', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (2340, 147982, '2010-09-09', 2, '2010-10-04', 
    'I - CONSULTAR CADASTRO CONSUMO/REVENDA - LAUDO TECNICO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (123401, 87106, '2010-09-09', 2, '2010-10-04', 
    'I - CONSUMO/REVENSA - LAUDO TECNICO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (123402, 76384, '2010-09-09', 2, '2010-10-04', 
    'I - CONSUMO/REVENSA - LAUDO TECNICO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (123403, 84700, '2010-09-09', 2, '2010-10-04', 
    'I - CONSUMO/REVENSA - LAUDO TECNICO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (123404, 34126, '2010-09-09', 2, '2010-10-04', 
    'I - CONSUMO/REVENSA - LAUDO TECNICO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (123405, 76805, '2010-09-09', 2, '2010-10-04', 
    'I - CONSUMO/REVENSA - LAUDO TECNICO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (12341, 264075, '2010-09-09', 2, '2010-10-04', 
    'faturr e entregar urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (1822, 154172, '2010-09-09', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (129108, 268313, '2010-09-09', 2, '2010-09-13', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4809, 23752, '2010-09-09', 2, '2010-12-10', 
    'I - Produzir e faturar em 29/10/2010.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4808, 229903, '2010-09-09', 2, '2010-10-29', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909040, 222810, '2010-09-09', 2, '2010-09-20', 
    'urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909041, 222810, '2010-09-09', 2, '2010-11-01', 
    'I - URGENTEE..');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909042, 211117, '2010-09-09', 2, '2010-10-04', 
    'IMEDIATO');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (79570, 990990, '2010-09-09', 3, '2010-09-13', 
    'Teste');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909043, 51233, '2010-09-09', 2, '2010-11-01', 
    'I-');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (965239, 190608, '2010-09-09', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (22700, 1902, '2010-09-09', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (932588, 283991, '2010-09-09', 2, '2010-09-27', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784246, 274810, '2010-09-09', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784247, 182826, '2010-09-09', 2, '2010-09-13', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784248, 186589, '2010-09-09', 2, '2010-10-19', 
    'ALTERADO COND. DE PAGTO CONFORME SOLICITACAO DE RENATO - VENDEDOR');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (22551, 39322, '2010-09-09', 2, '2010-09-13', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784249, 178926, '2010-09-09', 2, '2010-11-22', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (288288, 250791, '2010-09-09', 2, '2010-09-13', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909044, 261165, '2010-09-09', 2, '2010-09-20', 
    'urgente..');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909045, 268895, '2010-09-09', 2, '2010-10-04', 
    'urgente 180, 200 e 300 pode faturar parcial');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814497, 142883, '2010-09-09', 2, '2010-09-13', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (909046, 216100, '2010-09-09', 2, '2010-10-04', 
    'I- urgentissimo...');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615721, 282529, '2010-09-09', 2, '2010-09-24', 
    'Deposito ok Elizandra');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615717, 170267, '2010-09-09', 2, '2010-09-24', 
    'NATAL');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4806, 61018, '2010-09-09', 2, '2010-10-04', 
    'Faturar 09/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (22701, 212628, '2010-09-09', 2, '2010-10-18', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784250, 178926, '2010-09-09', 2, '2010-12-06', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (92006, 270849, '2010-09-10', 2, '2010-10-05', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (23427, 158917, '2010-09-10', 2, '2010-10-05', 
    'I - FATURAR 06/10 ENTREGAR DIA 08 - ARTE APROVADA MAIL 09/10');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73487, 224219, '2010-09-10', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4810, 257028, '2010-09-10', 2, '2010-09-20', 
    'Faturar 10/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (520172, 80373, '2010-09-10', 2, '2010-10-19', 
    'I-SOLICITANTE SR. ROBSON-AUT. SRA.VANUSA AUTORIZOU. FATURAR SOMENTE 84CXS');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (13365, 243418, '2010-09-10', 2, '2010-09-18', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4811, 254096, '2010-09-10', 2, '2010-09-20', 
    'Faturar 10/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (4812, 107514, '2010-09-10', 2, '2010-09-13', 
    'Faturar 10/09/2010');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615240, 281689, '2010-09-10', 2, '2010-11-02', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (987651, 268720, '2010-09-10', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (987659, 262889, '2010-09-10', 2, '2010-10-12', 
    'urgenbte');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (33365, 255912, '2010-09-10', 2, '2010-11-08', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814498, 280704, '2010-09-10', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814499, 273759, '2010-09-10', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814500, 229822, '2010-09-10', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (14611, 23540, '2010-09-10', 2, '2010-12-01', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (91023, 106640, '2010-09-10', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (911024, 106640, '2010-09-10', 2, '2010-09-15', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910009, 56103, '2010-09-10', 2, '2010-10-04', 
    'urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910010, 222895, '2010-09-10', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73488, 143847, '2010-09-10', 2, '2010-09-20', 
    'OPTANTE PELO SIMPLES NACIONAL - S.T. = 3,48%');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (73489, 292494, '2010-09-10', 2, '2010-10-05', 
    'I - OPTANTE PELO SIMPLES NACIONAL - S.T. = 3,48% -');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480518, 290181, '2010-09-10', 2, '2010-11-02', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480519, 218464, '2010-09-10', 2, '2010-11-02', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (719208, 66176, '2010-09-10', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (65463, 287300, '2010-09-10', 2, '2010-09-13', 
    'Pedido p/ Stela');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814501, 121703, '2010-09-10', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (759204, 147206, '2010-09-10', 2, '2010-10-06', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910011, 278025, '2010-09-10', 2, '2010-09-21', 
    'retira');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (19649, 76805, '2010-09-10', 3, '2010-10-05', 
    'TESTE TI');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910012, 56642, '2010-09-10', 2, '2010-09-13', 
    'retira');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131796, 280577, '2010-09-10', 2, '2010-10-05', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (131797, 283967, '2010-09-10', 2, '2010-10-05', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (480520, 232653, '2010-09-10', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (12366, 92827, '2010-09-10', 2, '2010-09-27', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814503, 259616, '2010-09-10', 2, '2010-10-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (814502, 151246, '2010-09-10', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (12367, 286281, '2010-09-10', 2, '2010-10-05', 
    'I.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (12368, 289965, '2010-09-10', 2, '2010-09-20', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (765800, 92940, '2010-09-10', 2, '2010-09-20', 
    'embalagemsantacruz@via.com.br');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (623461, 19704, '2010-09-10', 2, '2010-09-20', 
    'urgente');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615784, 25364, '2010-09-10', 2, '2010-09-24', 
    'NATAL');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615785, 2569, '2010-09-10', 3, '2010-09-17', 
    'Incluido no 615786');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615781, 141828, '2010-09-10', 2, '2010-09-24', 
    'ENTREGAR URGENTE');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615782, 68381, '2010-09-10', 2, '2010-09-24', 
    'NATAL');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615783, 166693, '2010-09-10', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615774, 181102, '2010-09-10', 2, '2010-10-08', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615778, 288535, '2010-09-10', 3, '2010-09-17', 
    'Marcos via email solicitou cancelar o pedido - Motivo -  duplicidade com o pedido 615222.');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615779, 65064, '2010-09-10', 2, '2010-10-01', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615777, 283010, '2010-09-10', 2, '2010-10-05', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (174106, 174106, '2010-09-10', 2, '2010-09-20', 
    'Urgente via e-mail Clodoaldo');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (541123, 123005, '2010-09-10', 2, '2010-10-05', 
    'CP550 MARIETTA');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (879631, 123005, '2010-09-10', 2, '2010-10-26', 
    'I - CP330 RHELKS');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784251, 198404, '2010-09-10', 2, '2010-09-27', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (784252, 279358, '2010-09-10', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (12556, 181021, '2010-09-10', 2, '2010-10-04', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615786, 2569, '2010-09-10', 2, '2010-10-08', 
    NULL);
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615787, 283428, '2010-09-10', 2, '2010-10-05', 
    'I - IMPRESSO PIZZA HUT ENTREGAR DIA 17/ 09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (615790, 266388, '2010-09-10', 3, '2010-09-28', 
    'PEDIDO 0249155028461 - VENC.FIXO 28/09/2010igual pedido 615565');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (910013, 52337, '2010-09-10', 3, '2010-09-15', 
    'ENTREGAR ATE 16/09');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (6414, 20150, '2010-09-10', 2, '2010-11-03', 
    'I. INCLUSAO DE POTES+TAMPAS LISOS, DEVIDO ATRASONOS IMPRESSOS = ZECA');
Insert into pedidos
   (nr_pedido, cd_cliente, dt_emissao, id_situacao, dt_entrega, 
    ds_observacao)
 Values
   (13366, 6220, '2010-09-10', 2, '2011-01-10', 
    'Sr. Mario via email solicitou cancelar o saldo do pedido.');
